// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.Text.Json;
using System.Web;
using Corvus.Json.CodeGeneration;
using Microsoft.CodeAnalysis.CSharp;

namespace Corvus.Text.Json.CodeGeneration
{
    internal static partial class CodeGeneratorExtensions
    {
        /// <summary>
        /// Appends a blank line if the previous line ended with a closing brace.
        /// </summary>
        /// <param name="generator">The generator to which to append the separator line.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendSeparatorLine(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            if ((generator.ScopeType == ScopeType.Type &&
                    generator.EndsWith($";\n")) ||
                    generator.EndsWith("}\n") ||
                    generator.EndsWith("#endif\n") ||
                    generator.EndsWith(";\r\n") ||
                    generator.EndsWith("}\r\n") ||
                    generator.EndsWith("#endif\r\n"))
            {
                // Append a blank line
                generator.AppendLine();
            }

            return generator;
        }

        /// <summary>
        /// Emits the auto-generated header.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendAutoGeneratedHeader(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .AppendBlockIndent(
                """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """);
        }

        /// <summary>
        /// Append using statements for the given namespaces.
        /// </summary>
        /// <param name="generator">The generator to which to append usings.</param>
        /// <param name="namespaces">The namespace to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendUsings(this CodeGenerator generator, params ConditionalCodeSpecification[] namespaces)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            ConditionalCodeSpecification.AppendConditionalsInOrder(
                generator,
                namespaces,
                static (g, a, _) => Append(g, a));

            return generator;

            static void Append(CodeGenerator generator, Action<CodeGenerator> action)
            {
                generator.Append("using ");
                action(generator);
                generator.AppendLine(";");
            }
        }

        /// <summary>
        /// Append the text as paragraphs, splitting on newline and/or carriage return.
        /// </summary>
        /// <param name="generator">The generator to which to append the paragraphs.</param>
        /// <param name="paragraphs">The text containing the paragraphs to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendParagraphs(this CodeGenerator generator, string paragraphs)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(paragraphs, removeBlankLines: true);
            foreach (string line in lines)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                generator
                    .AppendLineIndent("/// <para>")
                    .AppendIndent("/// ")
                    .AppendLine(SymbolDisplay.FormatLiteral(HttpUtility.HtmlEncode(line), false))
                    .AppendLineIndent("/// </para>");
            }

            return generator;
        }

        /// <summary>
        /// Append a multi-line block of text at the given indent.
        /// </summary>
        /// <param name="generator">The generator to which to append the block.</param>
        /// <param name="block">The block to append.</param>
        /// <param name="trimWhitespaceOnlyLines">Whether to trim lines that are whitespace only.</param>
        /// <param name="omitLastLineEnd">If <see langword="true"/> then the last line is appended without an additional line-end, leaving
        /// the generator at the end of the block.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendBlockIndent(this CodeGenerator generator, string block, bool trimWhitespaceOnlyLines = true, bool omitLastLineEnd = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(block);

            for (int i = 0; i < lines.Length; i++)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                string line = lines[i];
                if (omitLastLineEnd && i == lines.Length - 1)
                {
                    generator
                        .AppendIndent(line);
                }
                else
                {
                    generator
                        .AppendLineIndent(line, trimWhitespaceOnlyLines);
                }
            }

            return generator;
        }

        /// <summary>
        /// Append a multi-line block of text at the given indent.
        /// </summary>
        /// <param name="generator">The generator to which to append the block.</param>
        /// <param name="block">The block to append.</param>
        /// <param name="trimWhitespaceOnlyLines">Whether to trim lines that are whitespace only.</param>
        /// <param name="omitLastLineEnd">If <see langword="true"/> then the last line is appended without an additional line-end, leaving
        /// the generator at the end of the block.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendBlockIndentWithHashOutdent(this CodeGenerator generator, string block, bool trimWhitespaceOnlyLines = true, bool omitLastLineEnd = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(block);

            for (int i = 0; i < lines.Length; i++)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                string line = lines[i];
                if (omitLastLineEnd && i == lines.Length - 1)
                {
                    if (line[0] == '#')
                    {
                        generator.Append(line);
                    }
                    else
                    {
                        generator
                            .AppendIndent(line);
                    }
                }
                else
                {
                    if (line.Length > 0 && line[0] == '#')
                    {
                        generator.AppendLine(line);
                    }
                    else
                    {
                        generator
                            .AppendLineIndent(line, trimWhitespaceOnlyLines);
                    }
                }
            }

            return generator;
        }

        /// <summary>
        /// Append a multi-line block of text at the given indent, with a given line prefix.
        /// </summary>
        /// <param name="generator">The generator to which to append the block.</param>
        /// <param name="block">The block to append.</param>
        /// <param name="linePrefix">The prefix for each line.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendBlockIndentWithPrefix(this CodeGenerator generator, string block, string linePrefix)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(block);
            foreach (string line in lines)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                generator
                    .AppendIndent(linePrefix)
                    .AppendLine(line);
            }

            return generator;
        }

        /// <summary>
        /// Emits the parent/child nesting.
        /// </summary>
        /// <param name="generator">The generator to which to append the parent/child declaration nesting.</param>
        /// <param name="typeDeclaration">The type declaration being emitted.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginTypeDeclarationNesting(
            this CodeGenerator generator,
            TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            Stack<TypeDeclaration> parentTypes = new();

            TypeDeclaration? current = typeDeclaration.Parent();

            // We need to reverse the order, so we push them onto a stack...
            while (current is not null)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                parentTypes.Push(current);
                current = current.Parent();
            }

            bool isFirst = true;

            // Just begin our namespace if we have no parents.
            if (parentTypes.Count == 0)
            {
                return generator
                    .BeginNamespace(typeDeclaration.DotnetNamespace());
            }

            // ...and then pop them off again.
            while (parentTypes.Count > 0)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                TypeDeclaration parent = parentTypes.Pop();

                if (isFirst)
                {
                    generator
                        .BeginNamespace(parent.DotnetNamespace());
                    isFirst = false;
                }

                generator
                    .AppendSeparatorLine()
                    .AppendDocumentation(parent)
                    .BeginPartialStructDeclaration(
                        parent.DotnetAccessibility(),
                        parent.DotnetTypeName());
            }

            return generator;
        }

        /// <summary>
        /// Closes off the parent/child nesting.
        /// </summary>
        /// <param name="generator">The generator to which to append the nested-type closing.</param>
        /// <param name="typeDeclaration">The type declaration being emitted.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator EndTypeDeclarationNesting(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            TypeDeclaration? current = typeDeclaration.Parent();
            while (current is not null)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                generator.EndClassStructOrEnumDeclaration();
                current = current.Parent();
            }

            return generator;
        }

        /// <summary>
        /// Append a namespace statement.
        /// </summary>
        /// <param name="generator">The generator to which to append usings.</param>
        /// <param name="ns">The namespace to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginNamespace(this CodeGenerator generator, string ns)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .Append("namespace ")
                .Append(ns)
                .AppendLine(";")
                .PushMemberScope(ns, ScopeType.TypeContainer);
        }

        /// <summary>
        /// Append a namespace statement.
        /// </summary>
        /// <param name="generator">The generator to which to append usings.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator EndNamespace(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .PopMemberScope();
        }

        /// <summary>
        /// Emits the start of a public static class declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <param name="dotnetTypeName">The .NET type name for the partial struct.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginPublicStaticClassDeclaration(this CodeGenerator generator, string dotnetTypeName)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string name = generator.GetTypeNameInScope(dotnetTypeName);
            return generator
                .AppendIndent("public static class ")
                .AppendLine(name)
                .AppendLineIndent("{")
                .PushMemberScope(name, ScopeType.Type)
                .ReserveNameIfNotReserved(name) // Reserve the name of the containing scope in its own scope
                .PushIndent();
        }

        /// <summary>
        /// Emits the start of a public static class declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <param name="dotnetTypeName">The .NET type name for the partial struct.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginPrivateStaticClassDeclaration(this CodeGenerator generator, string dotnetTypeName)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string name = generator.GetTypeNameInScope(dotnetTypeName);
            return generator
                .AppendIndent("private static class ")
                .AppendLine(name)
                .AppendLineIndent("{")
                .PushMemberScope(name, ScopeType.Type)
                .ReserveNameIfNotReserved(name) // Reserve the name of the containing scope in its own scope
                .PushIndent();
        }

        /// <summary>
        /// Emits the start of a partial struct declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <param name="accessibility">The accessibility for the generated type.</param>
        /// <param name="dotnetTypeName">The .NET type name for the partial struct.</param>
        /// <param name="interfaces">Interfaces to implement.</param>
        /// <param name="isReadOnly">Indicates whether to emit a readonly struct (defaults to 'true')</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginPartialStructDeclaration(
            this CodeGenerator generator,
            GeneratedTypeAccessibility accessibility,
            string dotnetTypeName,
            ConditionalCodeSpecification[]? interfaces = null,
            bool isReadOnly = true)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string accessibilityString = accessibility switch
            {
                GeneratedTypeAccessibility.Public => "public",
                GeneratedTypeAccessibility.Internal => "internal",
                _ => throw new ArgumentOutOfRangeException(nameof(accessibility)),
            };

            generator.ReserveNameIfNotReserved(dotnetTypeName);
            generator
                .AppendIndent(accessibilityString)
                .Append(isReadOnly ? " readonly partial struct " : " partial struct ")
                .AppendLine(dotnetTypeName);

            if (interfaces is ConditionalCodeSpecification[] conditionalSpecifications)
            {
                generator.PushIndent();
                ConditionalCodeSpecification.AppendConditionalsGroupingBlocks(generator, conditionalSpecifications, AppendInterface);
                generator.PopIndent();
            }

            return generator
                .AppendLineIndent("{")
                .PushMemberScope(dotnetTypeName, ScopeType.Type)
                .ReserveNameIfNotReserved(dotnetTypeName) // Reserve the name of the containing scope in its own scope
                .PushIndent();

            static void AppendInterface(CodeGenerator generator, Action<CodeGenerator> appendFunction, int elementIndexInConditionalBlock)
            {
                if (generator.IsCancellationRequested)
                {
                    return;
                }

                if (elementIndexInConditionalBlock == 0)
                {
                    generator.AppendIndent(": ");
                    appendFunction(generator);
                }
                else
                {
                    generator
                        .AppendLine(",")
                        .AppendIndent("  "); // Align with the ": "
                    appendFunction(generator);
                }
            }
        }

        /// <summary>
        /// Emits the start of a ref struct declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <param name="accessibility">The accessibility for the generated type.</param>
        /// <param name="dotnetTypeName">The .NET type name for the ref struct.</param>
        /// <param name="isReadOnly">If <see langword="true"/>, this will generate a <c>readonly</c> struct.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginRefStruct(
            this CodeGenerator generator,
            GeneratedTypeAccessibility accessibility,
            string dotnetTypeName,
            bool isReadOnly = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string accessibilityString = accessibility switch
            {
                GeneratedTypeAccessibility.Public => "public",
                GeneratedTypeAccessibility.Internal => "internal",
                GeneratedTypeAccessibility.Private => "private",
                _ => throw new ArgumentOutOfRangeException(nameof(accessibility)),
            };

            generator.ReserveNameIfNotReserved(dotnetTypeName);
            generator
                .AppendIndent(accessibilityString)
                .Append(isReadOnly ? " readonly" : "")
                .Append(" ref struct ")
                .AppendLine(dotnetTypeName);

            return generator
                .AppendLineIndent("{")
                .PushMemberScope(dotnetTypeName, ScopeType.Type)
                .ReserveNameIfNotReserved(dotnetTypeName) // Reserve the name of the containing scope in its own scope
                .PushIndent();
        }

        /// <summary>
        /// Emits the start of an enum declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <param name="accessibility">The accessibility for the generated type.</param>
        /// <param name="dotnetTypeName">The .NET type name for the enum.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginEnum(
            this CodeGenerator generator,
            GeneratedTypeAccessibility accessibility,
            string dotnetTypeName)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string accessibilityString = accessibility switch
            {
                GeneratedTypeAccessibility.Public => "public",
                GeneratedTypeAccessibility.Internal => "internal",
                GeneratedTypeAccessibility.Private => "private",
                _ => throw new ArgumentOutOfRangeException(nameof(accessibility)),
            };

            generator.ReserveNameIfNotReserved(dotnetTypeName);
            generator
                .AppendIndent(accessibilityString, " enum ")
                .AppendLine(dotnetTypeName);

            return generator
                .AppendLineIndent("{")
                .PushMemberScope(dotnetTypeName, ScopeType.Type)
                .ReserveNameIfNotReserved(dotnetTypeName) // Reserve the name of the containing scope in its own scope
                .PushIndent();
        }

        /// <summary>
        /// Emits the end of a class or struct declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the end of the struct declaration.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator EndClassStructOrEnumDeclaration(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .PopMemberScope()
                .PopIndent()
                .AppendLineIndent("}");
        }

        /// <summary>
        /// Begin a method declaration for an explicit name which will be reserved in the scope.
        /// </summary>
        /// <param name="generator">The generator to which to append the method.</param>
        /// <param name="visibilityAndModifiers">The visibility and modifiers for the method.</param>
        /// <param name="returnType">The return type of the method.</param>
        /// <param name="methodName">The method name, which will be reserved in the scope.</param>
        /// <param name="parameters">The parameter list.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginReservedMethodDeclaration(
            this CodeGenerator generator,
            string visibilityAndModifiers,
            string returnType,
            string methodName,
            params MethodParameter[] parameters)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .AppendSeparatorLine()
                .AppendIndent(visibilityAndModifiers)
                .Append(' ')
                .Append(returnType)
                .Append(' ')
                .Append(methodName)
                .ReserveName(methodName) // Reserve the method name in the parent scope
                .PushMemberScope(methodName, ScopeType.Method) // Then move to the method scope before appending parameters
                .AppendParameterList(parameters)
                .AppendLineIndent("{")
                .PushIndent();
        }

        /// <summary>
        /// Append a parameter list. This will produce the parameters on a single line
        /// for 0, 1, or 2 parameters, and an indented multi-line list for 3 or more parameters.
        /// </summary>
        /// <param name="generator">The generator to which to append the parameter list.</param>
        /// <param name="parameters">The parameter list.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendParameterList(
            this CodeGenerator generator,
            params MethodParameter[] parameters)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            if (parameters.Length < 3)
            {
                return AppendParameterListSingleLine(generator, parameters);
            }

            return AppendParameterListIndent(generator, parameters);
        }

        /// <summary>
        /// Append a parameter list on a single line.
        /// </summary>
        /// <param name="generator">The generator to which to append the parameter list.</param>
        /// <param name="parameters">The parameter list.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendParameterListSingleLine(CodeGenerator generator, MethodParameter[] parameters)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            if (parameters.Length == 0)
            {
                // If we have no parameters, just emit the brackets.
                return generator.AppendLine("()");
            }

            generator.Append("(");
            bool first = true;

            foreach (MethodParameter parameter in parameters)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                if (first)
                {
                    first = false;
                }
                else
                {
                    generator.Append(", ");
                }

                generator.AppendParameter(parameter);
            }

            return generator
                .AppendLine(")");
        }

        /// <summary>
        /// Append a parameter list on multiple lines, indented.
        /// </summary>
        /// <param name="generator">The generator to which to append the parameter list.</param>
        /// <param name="parameters">The parameter list.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendParameterListIndent(CodeGenerator generator, MethodParameter[] parameters)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            if (parameters.Length == 0)
            {
                // If we have no parameters, just emit the brackets.
                return generator.AppendLine("()");
            }

            generator.AppendLine("(");
            generator.PushIndent();
            bool first = true;

            foreach (MethodParameter parameter in parameters)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                if (first)
                {
                    first = false;
                }
                else
                {
                    generator.AppendLine(",");
                }

                generator.AppendParameterIndent(parameter);
            }

            return generator
                .PopIndent()
                .AppendLine(")");
        }

        /// <summary>
        /// Append a parameter in a parameter list.
        /// </summary>
        /// <param name="generator">The generator to which to append the parameter.</param>
        /// <param name="parameter">The parameter to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendParameterIndent(
            this CodeGenerator generator,
            MethodParameter parameter)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string name = parameter.GetName(generator, isDeclaration: true);

            if (!string.IsNullOrEmpty(parameter.Modifiers))
            {
                generator
                    .AppendIndent(parameter.Modifiers)
                    .Append(' ')
                    .Append(parameter.Type);
            }
            else
            {
                generator
                    .AppendIndent(parameter.Type);
            }

            if (parameter.TypeIsNullable)
            {
                generator
                    .Append('?');
            }

            generator
                .Append(' ')
                .Append(name);

            if (!string.IsNullOrEmpty(parameter.DefaultValue))
            {
                generator
                    .Append(" = ")
                    .Append(parameter.DefaultValue);
            }

            return generator;
        }

        /// <summary>
        /// Append a parameter in a parameter list.
        /// </summary>
        /// <param name="generator">The generator to which to append the parameter.</param>
        /// <param name="parameter">The parameter to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendParameter(
            this CodeGenerator generator,
            MethodParameter parameter)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string name = parameter.GetName(generator, isDeclaration: true);

            if (!string.IsNullOrEmpty(parameter.Modifiers))
            {
                generator
                    .Append(parameter.Modifiers)
                    .Append(' ');
            }

            generator
                .Append(parameter.Type);

            if (parameter.TypeIsNullable)
            {
                generator
                    .Append('?');
            }

            generator
                .Append(' ')
                .Append(name);

            if (!string.IsNullOrEmpty(parameter.DefaultValue))
            {
                generator
                    .Append(" = ")
                    .Append(parameter.DefaultValue);
            }

            return generator;
        }

        public static CodeGenerator AppendBackingFields(this CodeGenerator generator, bool forMutable = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            if (forMutable)
            {
                return generator
                    .AppendLineIndent("private readonly IMutableJsonDocument _parent;")
                    .AppendLineIndent("private readonly int _idx;")
                    .AppendLineIndent("private ulong _documentVersion;");
            }

            return generator
                .AppendLineIndent("private readonly IJsonDocument _parent;")
                .AppendLineIndent("private readonly int _idx;");
        }

        /// <summary>
        /// Append the default constructor for the type declaration.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the constructor.</param>
        /// <param name="forMutable">Append the version for a mutable instance.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendInternalConstructor(this CodeGenerator generator, TypeDeclaration typeDeclaration, bool forMutable = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .AppendSeparatorLine()
                .AppendLineIndent("/// <summary>")
                .AppendIndent("/// Initializes a new instance of the ")
                .AppendTypeAsSeeCref(forMutable ? "Mutable" : typeDeclaration.DotnetTypeName())
                .AppendLine(" struct.")
                .AppendLineIndent("/// </summary>")
                .AppendLineIndent("/// <param name=\"value\">The value from which to construct the instance.</param>")
                .AppendIndent("internal ")
                .Append(forMutable ? "Mutable" : typeDeclaration.DotnetTypeName())
                .AppendLine("(IJsonDocument parent, int idx)")
                .AppendLineIndent("{")
                .PushIndent();

            if (forMutable)
            {
                generator
                    .AppendLineIndent("Debug.Assert(idx >= 0);")
                    .AppendLineIndent("_parent = (IMutableJsonDocument)parent;")
                    .AppendLineIndent("_idx = idx;")
                    .AppendLineIndent("_documentVersion = _parent?.Version ?? 0;");
            }
            else
            {
                generator
                    .AppendLineIndent("Debug.Assert(idx >= 0);")
                    .AppendLineIndent("_parent = parent;")
                    .AppendLineIndent("_idx = idx;");
            }

            return generator
                .PopIndent()
                .AppendLineIndent("}");
        }

        /// <summary>
        /// Append the schema location static property for the type declaration.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the property.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendSchemaLocationStaticProperty(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("SchemaLocation")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                """
            /// <summary>
            /// Gets the schema location from which this type was generated.
            /// </summary>
            """)
                .AppendIndent("public static string SchemaLocation { get; } = ")
                .Append(SymbolDisplay.FormatLiteral(typeDeclaration.RelativeSchemaLocation, true))
                .AppendLine(";");
        }

        /// <summary>
        /// Append the static property which provides a default instance of the type declaration.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the property.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendDefaultInstanceStaticProperty(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .ReserveName("DefaultInstance")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                """
            /// <summary>
            /// Gets the default instance.
            /// </summary>
            """)
                .AppendIndent("public static ")
                .Append(typeDeclaration.DotnetTypeName())
                .Append(" DefaultInstance { get; }");

            return typeDeclaration.DefaultValue().ValueKind switch
            {
                JsonValueKind.Undefined => generator.AppendLine(),
                JsonValueKind.Null => generator
                                        .Append(" = ")
                                        .Append(typeDeclaration.DotnetTypeName())
                                        .AppendLine(".ParseValue(\"null\"u8);"),
                JsonValueKind.True => generator
                                        .Append(" = ")
                                        .Append(typeDeclaration.DotnetTypeName())
                                        .AppendLine(".ParseValue(\"true\"u8);"),
                JsonValueKind.False => generator
                                        .Append(" = ")
                                        .Append(typeDeclaration.DotnetTypeName())
                                        .AppendLine(".ParseValue(\"false\"u8);"),
                _ => generator
                        .Append(" = ")
                        .Append(typeDeclaration.DotnetTypeName())
                        .Append(".ParseValue(")
                        .Append(SymbolDisplay.FormatLiteral(typeDeclaration.DefaultValue().GetRawText(), true))
                        .AppendLine("u8);"),
            };
        }

        /// <summary>
        /// Append a property which gets the <see cref="JsonValueKind"/> for the instance.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// 
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendValueKindProperty(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("ValueKind")
                .AppendSeparatorLine()
                .AppendLineIndent("/// <inheritdoc/>")
                .AppendLineIndent("public JsonValueKind ValueKind => TokenType.ToValueKind();");
        }

        /// <summary>
        /// Append a property which gets the <c>JsonTokenType</c> for the instance.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// 
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendTokenTypeProperty(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("TokenType")
                .AppendSeparatorLine()
                .AppendLineIndent("[DebuggerBrowsable(DebuggerBrowsableState.Never)]")
                .AppendLineIndent("private JsonTokenType TokenType => _parent?.GetJsonTokenType(_idx) ?? JsonTokenType.None;");
        }

        public static CodeGenerator AppendCheckValidInstance(this CodeGenerator generator, bool forMutable = false)
        {
            generator
                .ReserveName("CheckValidInstance")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                """
                private void CheckValidInstance()
                {
                    if (_parent == null)
                    {
                        throw new InvalidOperationException();
                    }
                """);

            if (forMutable)
            {
                generator
                    .AppendSeparatorLine()
                    .PushIndent()
                    .AppendBlockIndent(
                        """
                        if (_documentVersion != _parent.Version)
                        {
                            throw new InvalidOperationException();
                        }
                        """)
                    .PopIndent();
            }

            return generator
                .AppendLineIndent("}")
                .AppendSeparatorLine()
                .AppendLineIndent("/// <inheritdoc/>")
                .AppendLineIndent("void IJsonElement.CheckValidInstance() => CheckValidInstance();");
        }

        /// <summary>
        /// Appends the From static factory method.
        /// to JsonAny.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration to which to convert.</param>
        /// <param name="forMutable">If <see langword="true"/> append the version for a mutable instance.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendFromFactoryMethod(this CodeGenerator generator, TypeDeclaration typeDeclaration, bool forMutable = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("From")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <summary>
                    /// Gets an instance of the JSON value from another element.
                    /// </summary>
                    /// <param name="value">The <see cref="IJsonElement{T}"/> value from which to instantiate the instance.</param>
                    /// <returns>An instance of this type, initialized from the JSON element.</returns>                
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    """)
                .AppendLineIndent("public static ", forMutable ? "Mutable" : typeDeclaration.DotnetTypeName(), " From<T>(in T instance)")
                .PushIndent()
                    .AppendLineIndent(forMutable ? "where T : struct, IMutableJsonElement<T>" : "where T : struct, IJsonElement<T>")
                .PopIndent()
                .AppendLineIndent("{")
                .PushIndent()
                    .AppendLineIndent("return new(instance.ParentDocument, instance.ParentDocumentIndex);")
                .PopIndent()
                .AppendLineIndent("}");
        }

        /// <summary>
        /// Appends the CreateInstance static factory method.
        /// to JsonAny.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration to which to convert.</param>
        /// <param name="forMutable">Generate a method for the mutable instance.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendCreateInstance(this CodeGenerator generator, TypeDeclaration typeDeclaration, bool forMutable = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .ReserveName("CreateInstance")
                .AppendSeparatorLine()
                .AppendLine("#if NET");

            if (forMutable)
            {
                return generator
                    .AppendLineIndent("static Mutable IJsonElement<Mutable>.CreateInstance(IJsonDocument parentDocument, int parentDocumentIndex) => new(parentDocument, parentDocumentIndex);")
                    .AppendLine("#endif");
            }

            return generator
                .AppendLineIndent("static ", typeDeclaration.DotnetTypeName(), " IJsonElement<", typeDeclaration.DotnetTypeName(), ">.CreateInstance(IJsonDocument parentDocument, int parentDocumentIndex) => new(parentDocument, parentDocumentIndex);")
                .AppendLine("#endif");
        }

        /// <summary>
        /// Appends the JsonElement conversion operator.
        /// to JsonAny.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration to which to convert.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendJsonElementConversionOperator(this CodeGenerator generator, TypeDeclaration typeDeclaration, bool forMutable = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <summary>
                    /// Converts the instance to a JsonElement.
                    /// </summary>
                    /// <param name="value">The instance of this type.</param>
                    /// <returns>An instance of JsonElement, initialized from the <see cref="IJsonElement{T}"/>.</returns>                
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    """)
                .AppendLineIndent("public static implicit operator JsonElement(", forMutable ? "Mutable" : typeDeclaration.DotnetTypeName(), " instance)")
                .AppendLineIndent("{")
                .PushIndent()
                    .AppendLineIndent("return JsonElement.From(instance);")
                .PopIndent()
                .AppendLineIndent("}");
        }

        /// <summary>
        /// Appends the conversion operators for a mutable instance.
        /// to JsonAny.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration to which to convert.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendMutableConversionOperators(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("FromJson")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <summary>
                    /// Converts an immutable instance to a mutable instance, if the instance is backed by a mutable document.
                    /// </summary>
                    /// <param name="value">The instance of this type.</param>
                    /// <returns>A mutable instance.</returns>
                    /// <exception cref="FormatException">Thrown if the instance is not backed by a mutable document.</exception>
                    """)
                .AppendLineIndent("public static explicit operator Mutable(", typeDeclaration.DotnetTypeName(), " instance)")
                .AppendLineIndent("{")
                .PushIndent()
                    .AppendLineIndent("if (instance._parent is not IMutableJsonDocument doc)")
                    .AppendLineIndent("{")
                    .PushIndent()
                        .AppendLineIndent("CodeGenThrowHelper.ThrowFormatException();")
                        .AppendLineIndent("return default;")
                    .PopIndent()
                    .AppendLineIndent("}")
                    .AppendSeparatorLine()
                    .AppendLineIndent("return new(doc, instance._idx);")
                .PopIndent()
                .AppendLineIndent("}")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <summary>
                    /// Converts the instance to a JsonElement.
                    /// </summary>
                    /// <param name="value">The instance of this type.</param>
                    /// <returns>An instance of JsonElement, initialized from the <see cref="IJsonElement{T}"/>.</returns>                
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    """)
                .AppendLineIndent("public static implicit operator ", typeDeclaration.DotnetTypeName(), "(Mutable instance)")
                .AppendLineIndent("{")
                .PushIndent()
                    .AppendLineIndent("return new(instance._parent, instance._idx);")
                .PopIndent()
                .AppendLineIndent("}");
            ;
        }

        /// <summary>
        /// Append the Equals() method overloads.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to produce the methods.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendEqualsOverloads(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .ReserveNameIfNotReserved("Equals")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <inheritdoc/>
                    public override bool Equals(object? obj)
                    {
                        return
                    """)
                .PushIndent()
                .PushIndent()
                .AppendLineIndent("(obj is IJsonElement value && Equals(new ", typeDeclaration.DotnetTypeName(), "(value.ParentDocument, value.ParentDocumentIndex))) ||")
                .PopIndent()
                .PopIndent()
                .AppendBlockIndent(
                    """
                            (obj is null && this.IsNull());
                    }

                    /// <summary>
                    /// Equality comparison.
                    /// </summary>
                    /// <param name="other">The other item with which to compare.</param>
                    /// <returns><see langword="true"/> if the values were equal.</returns>
                    """)
                .AppendLineIndent("public bool Equals<T>(in T other)")
                .PushIndent()
                    .AppendLineIndent("where T : struct, IJsonElement")
                .PopIndent()
                .AppendLineIndent("{")
                .PushIndent();

            bool appendDefault = true;
            if (typeDeclaration.Format() is string format)
            {
                appendDefault = !FormatHandlerRegistry.Instance.FormatHandlers.AppendFormatEqualsTBody(generator, typeDeclaration, format);
            }

            if (appendDefault)
            {
                generator
                    .AppendLineIndent("return JsonElementHelpers.DeepEquals(this, other);");
            }

            return generator
                .PopIndent()
                .AppendLineIndent("}");
        }

        /// <summary>
        /// Append the WriteTo() method.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// 
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendWriteToMethod(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
            .ReserveName("WriteTo")
            .AppendSeparatorLine()
            .AppendLineIndent("/// <inheritdoc/>")
            .AppendLineIndent("public void WriteTo(Utf8JsonWriter writer)")
            .AppendLineIndent("{")
            .PushIndent()
                .AppendLineIndent("CheckValidInstance();")
                .AppendLineIndent("_parent.WriteElementTo(_idx, writer);")
            .PopIndent()
            .AppendLineIndent("}");
        }

        /// <summary>
        /// Appends the GetHashCode() and ToString() methods.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to append the methods.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendGetHashCodeAndToStringMethods(this CodeGenerator generator, bool forMutable)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .ReserveNameIfNotReserved("GetHashCode")
                .ReserveNameIfNotReserved("ToString")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <inheritdoc/>
                    public override int GetHashCode()
                    {
                        if (_parent == null)
                        {
                            return 0;
                        }

                        return _parent.GetHashCode(_idx);
                    }
                    """)
                .AppendSeparatorLine();


            if (forMutable)
            {
                return generator
                    .AppendBlockIndent(
                        """
                        /// <inheritdoc/>
                        public override string ToString()
                        {
                            if (_parent == null || _documentVersion != _parent.Version)
                            {
                                return string.Empty;
                            }

                            return _parent.ToString(_idx);
                        }
                        """);
            }
            else
            {
                return generator
                    .AppendBlockIndent(
                        """
                        /// <inheritdoc/>
                        public override string ToString()
                        {
                            if (_parent is null)
                            {
                                return string.Empty;
                            }

                            return _parent.ToString(_idx);
                        }
                        """);
            }
        }

        /// <summary>
        /// Append a standard debugger display attribute.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendDebuggerDisplay(this CodeGenerator generator, string? debuggerString = null)
        {
            return generator
                .AppendLineIndent("[DebuggerDisplay(\"", debuggerString ?? "{DebuggerDisplay,nq}", "\")]");
        }

        /// <summary>
        /// Append a standard debugger display property for the type declaration.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="forMutable">Generate for the mutable instance.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendDebuggerDisplayProperty(this CodeGenerator generator, TypeDeclaration typeDeclaration, bool forMutable = false)
        {
            return generator
                .ReserveName("DebuggerDisplay")
                .AppendSeparatorLine()
                .AppendLineIndent("[DebuggerBrowsable(DebuggerBrowsableState.Never)]")
                .AppendLineIndent("private string DebuggerDisplay => $\"", typeDeclaration.DotnetTypeName(), forMutable ? ".Mutable" : "",  ": ValueKind = {ValueKind} : \\\"{ToString()}\\\"\";");
        }

        /// <summary>
        /// Appends explicit interface property implementations for <c>IJsonElement</c> to the generated type.
        /// </summary>
        /// <param name="generator">The code generator to which to append the explicit interface implementations.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendIJsonElementExplicitImplementation(this CodeGenerator generator)
        {
            return generator
                .ReserveNameIfNotReserved("ParentDocument")
                .ReserveNameIfNotReserved("ParentDocumentIndex")
                .ReserveNameIfNotReserved("TokenType")
                .ReserveNameIfNotReserved("ValueKind")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                """
                [DebuggerBrowsable(DebuggerBrowsableState.Never)]
                IJsonDocument IJsonElement.ParentDocument => _parent;

                [DebuggerBrowsable(DebuggerBrowsableState.Never)]
                int IJsonElement.ParentDocumentIndex => _idx;

                [DebuggerBrowsable(DebuggerBrowsableState.Never)]
                JsonTokenType IJsonElement.TokenType => TokenType;

                [DebuggerBrowsable(DebuggerBrowsableState.Never)]
                JsonValueKind IJsonElement.ValueKind => ValueKind;
                """);
        }

        /// <summary>
        /// Append an ordinal name for a number.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="number">The number for which to generate the ordinal.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendOrdinalName(this CodeGenerator generator, int number)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                    .Append(number);

            if (number >= 11 && number <= 13)
            {
                return generator
                    .Append("th");
            }

            return (number % 10) switch
            {
                1 => generator.Append("st"),
                2 => generator.Append("nd"),
                3 => generator.Append("rd"),
                _ => generator.Append("th"),
            };
        }

        private static string[] NormalizeAndSplitBlockIntoLines(string block, bool removeBlankLines = false)
        {
            string normalizedBlock = block.Replace("\r\n", "\n");
            string[] lines = normalizedBlock.Split(['\n'], removeBlankLines ? StringSplitOptions.RemoveEmptyEntries : StringSplitOptions.None);
            return lines;
        }
    }
}
