// <copyright file="StandaloneEvaluatorGenerator.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Corvus.Json.CodeGeneration;
using Corvus.Json.CodeGeneration.Keywords;

namespace Corvus.Text.Json.CodeGeneration;

/// <summary>
/// Generates a standalone static evaluator class that performs full JSON Schema
/// validation and annotation collection, independent of generated types.
/// </summary>
internal static class StandaloneEvaluatorGenerator
{
    /// <summary>
    /// Generates a standalone evaluator for the given root type declaration.
    /// </summary>
    /// <param name="rootType">The root type declaration (before reduction).</param>
    /// <param name="options">The code generation options.</param>
    /// <param name="lineEnd">The line ending sequence.</param>
    /// <returns>A generated code file containing the evaluator, or <see langword="null"/> if generation is not applicable.</returns>
    public static GeneratedCodeFile? Generate(
        TypeDeclaration rootType,
        CSharpLanguageProvider.Options options,
        string lineEnd = "\r\n")
    {
        string evaluatorClassName = GetEvaluatorClassName(rootType);
        string ns = options.GetNamespace(rootType);

        var context = new GenerationContext(lineEnd);

        EmitFileHeader(context, options);
        EmitNamespaceOpen(context, ns);
        EmitClassOpen(context, evaluatorClassName);

        // Emit static fields (schema path providers, regex patterns, etc.)
        EmitStaticFields(context, rootType);

        // Emit public Evaluate<TElement> entry point
        EmitPublicEvaluateMethod(context, rootType);

        // Emit the root evaluation method
        var visited = new Dictionary<string, string>();
        EmitSchemaEvaluationMethod(context, rootType, "EvaluateRoot", visited);

        EmitClassClose(context);
        EmitNamespaceClose(context);

        string content = context.ToString();
        string fileName = evaluatorClassName + ".Evaluator";

        return new GeneratedCodeFile(fileName + options.FileExtension, content);
    }

    private static string GetEvaluatorClassName(TypeDeclaration rootType)
    {
        // Use the root type's dotnet name if available, otherwise derive from schema
        if (rootType.TryGetDotnetTypeName(out string? typeName))
        {
            return typeName + "Evaluator";
        }

        // For reduced types that have no dotnet name, derive from the schema location
        string location = rootType.LocatedSchema.Location.ToString();
        string safeName = MakeSafeIdentifier(location);
        return safeName + "Evaluator";
    }

    private static string MakeSafeIdentifier(string input)
    {
        var sb = new StringBuilder(input.Length);
        foreach (char c in input)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
            else if (sb.Length > 0 && sb[sb.Length - 1] != '_')
            {
                sb.Append('_');
            }
        }

        // Ensure it starts with a letter
        if (sb.Length == 0 || !char.IsLetter(sb[0]))
        {
            sb.Insert(0, "Schema");
        }

        return sb.ToString().TrimEnd('_');
    }

    private static void EmitFileHeader(GenerationContext context, CSharpLanguageProvider.Options options)
    {
        context.AppendLine("// <auto-generated/>");
        context.AppendLine("#nullable enable");
        context.AppendLine();

        if (options.AddExplicitUsings)
        {
            context.AppendLine("using System;");
            context.AppendLine("using System.Diagnostics;");
            context.AppendLine("using System.Diagnostics.CodeAnalysis;");
        }
        else
        {
            context.AppendLine("using System.Diagnostics;");
            context.AppendLine("using System.Diagnostics.CodeAnalysis;");
        }

        context.AppendLine("using System.Buffers;");
        context.AppendLine("using System.Buffers.Text;");
        context.AppendLine("using System.Runtime.CompilerServices;");
        context.AppendLine("using Corvus.Text.Json;");
        context.AppendLine("using Corvus.Text.Json.Internal;");
        context.AppendLine();
    }

    private static void EmitNamespaceOpen(GenerationContext context, string ns)
    {
        context.AppendLine($"namespace {ns};");
        context.AppendLine();
    }

    private static void EmitNamespaceClose(GenerationContext context)
    {
        // File-scoped namespace, no closing needed.
    }

    private static void EmitClassOpen(GenerationContext context, string className)
    {
        context.AppendLine("/// <summary>");
        context.AppendLine($"/// Standalone schema evaluator for the <c>{className.Replace("Evaluator", string.Empty)}</c> schema.");
        context.AppendLine("/// </summary>");
        context.AppendLine($"public static class {className}");
        context.AppendLine("{");
        context.PushIndent();
    }

    private static void EmitClassClose(GenerationContext context)
    {
        context.PopIndent();
        context.AppendLine("}");
    }

    private static void EmitStaticFields(GenerationContext context, TypeDeclaration rootType)
    {
        // TODO: Emit schema path providers, regex patterns, constants, etc.
        // These will be added as keyword handlers are implemented.
    }

    private static void EmitPublicEvaluateMethod(GenerationContext context, TypeDeclaration rootType)
    {
        bool useEvaluatedItems = rootType.RequiresItemsEvaluationTracking();
        bool useEvaluatedProperties = rootType.RequiresPropertyEvaluationTracking();

        context.AppendLine("/// <summary>");
        context.AppendLine("/// Evaluates the given JSON element against this schema.");
        context.AppendLine("/// </summary>");
        context.AppendLine("/// <typeparam name=\"TElement\">The type of JSON element.</typeparam>");
        context.AppendLine("/// <param name=\"instance\">The instance to evaluate.</param>");
        context.AppendLine("/// <param name=\"resultsCollector\">The optional results collector.</param>");
        context.AppendLine("/// <returns><see langword=\"true\"/> if the instance is valid against the schema.</returns>");
        context.AppendLine("public static bool Evaluate<TElement>(");
        context.PushIndent();
        context.AppendLine("in TElement instance,");
        context.AppendLine("IJsonSchemaResultsCollector? resultsCollector = null)");
        context.PopIndent();
        context.PushIndent();
        context.AppendLine("where TElement : struct, IJsonElement<TElement>");
        context.PopIndent();
        context.AppendLine("{");
        context.PushIndent();

        context.AppendLine($"JsonSchemaContext context = JsonSchemaContext.BeginContext(");
        context.PushIndent();
        context.AppendLine("instance.ParentDocument,");
        context.AppendLine("instance.ParentDocumentIndex,");
        context.AppendLine($"usingEvaluatedItems: {(useEvaluatedItems ? "true" : "false")},");
        context.AppendLine($"usingEvaluatedProperties: {(useEvaluatedProperties ? "true" : "false")},");
        context.AppendLine("resultsCollector: resultsCollector);");
        context.PopIndent();
        context.AppendLine();
        context.AppendLine("try");
        context.AppendLine("{");
        context.PushIndent();
        context.AppendLine("EvaluateRoot(instance.ParentDocument, instance.ParentDocumentIndex, ref context);");
        context.AppendLine("context.EndContext();");
        context.AppendLine("return context.IsMatch;");
        context.PopIndent();
        context.AppendLine("}");
        context.AppendLine("finally");
        context.AppendLine("{");
        context.PushIndent();
        context.AppendLine("context.Dispose();");
        context.PopIndent();
        context.AppendLine("}");

        context.PopIndent();
        context.AppendLine("}");
        context.AppendLine();
    }

    private static void EmitSchemaEvaluationMethod(
        GenerationContext context,
        TypeDeclaration typeDeclaration,
        string methodName,
        Dictionary<string, string> visited)
    {
        // Check for boolean schema
        if (typeDeclaration.LocatedSchema.IsBooleanSchema)
        {
            EmitBooleanSchemaMethod(context, typeDeclaration, methodName);
            return;
        }

        context.AppendLine($"private static void {methodName}(");
        context.PushIndent();
        context.AppendLine("IJsonDocument parentDocument,");
        context.AppendLine("int parentIndex,");
        context.AppendLine("ref JsonSchemaContext context)");
        context.PopIndent();
        context.AppendLine("{");
        context.PushIndent();

        // Token type check if needed
        if (RequiresTokenType(typeDeclaration))
        {
            context.AppendLine("JsonTokenType tokenType = parentDocument.GetJsonTokenType(parentIndex);");
            context.AppendLine();
        }

        context.AppendLine("Debug.Assert(parentDocument.GetJsonTokenType(parentIndex) is not");
        context.PushIndent();
        context.AppendLine("(JsonTokenType.None or");
        context.AppendLine("JsonTokenType.EndObject or");
        context.AppendLine("JsonTokenType.EndArray));");
        context.PopIndent();
        context.AppendLine();

        // TODO: Emit keyword-specific validation code. Each keyword handler (type, const, enum,
        // format, string, number, object, array, composition, conditional, ref, unevaluated,
        // annotations) will add its emission code here.
        context.PopIndent();
        context.AppendLine("}");
    }

    private static void EmitBooleanSchemaMethod(
        GenerationContext context,
        TypeDeclaration typeDeclaration,
        string methodName)
    {
        bool isTrue = typeDeclaration.LocatedSchema.Schema.ValueKind == JsonValueKind.True;

        context.AppendLine($"private static void {methodName}(");
        context.PushIndent();
        context.AppendLine("IJsonDocument parentDocument,");
        context.AppendLine("int parentIndex,");
        context.AppendLine("ref JsonSchemaContext context)");
        context.PopIndent();
        context.AppendLine("{");
        context.PushIndent();

        if (!isTrue)
        {
            // Boolean false schema: always fails
            context.AppendLine("context.EvaluatedKeyword(false, JsonSchemaEvaluation.BooleanSchemaFalse, \"\"u8);");
        }

        // Boolean true schema: always succeeds (no code needed, context defaults to match)
        context.PopIndent();
        context.AppendLine("}");
    }

    private static bool RequiresTokenType(TypeDeclaration typeDeclaration)
    {
        // If the schema has any type-sensitive keywords, we need the token type
        return typeDeclaration.Keywords().Any(k =>
            k is ICoreTypeValidationKeyword or
                 IObjectValidationKeyword or
                 IArrayValidationKeyword or
                 IStringValidationKeyword or
                 INumberValidationKeyword or
                 IFormatProviderKeyword);
    }

    /// <summary>
    /// Lightweight code builder with indentation support.
    /// </summary>
    internal sealed class GenerationContext
    {
        private readonly StringBuilder builder = new();
        private readonly string lineEnd;
        private int indentLevel;
        private string currentIndent = string.Empty;

        public GenerationContext(string lineEnd)
        {
            this.lineEnd = lineEnd;
        }

        public void PushIndent()
        {
            this.indentLevel++;
            this.currentIndent = new string(' ', this.indentLevel * 4);
        }

        public void PopIndent()
        {
            this.indentLevel--;
            this.currentIndent = this.indentLevel > 0
                ? new string(' ', this.indentLevel * 4)
                : string.Empty;
        }

        public void AppendLine()
        {
            this.builder.Append(this.lineEnd);
        }

        public void AppendLine(string line)
        {
            this.builder.Append(this.currentIndent);
            this.builder.Append(line);
            this.builder.Append(this.lineEnd);
        }

        public void Append(string text)
        {
            this.builder.Append(text);
        }

        public override string ToString()
        {
            return this.builder.ToString();
        }
    }
}