// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.Text.Json;
using System.Web;
using Corvus.Json.CodeGeneration;
using Microsoft.CodeAnalysis.CSharp;

namespace Corvus.Text.Json.CodeGeneration
{
    internal static partial class CodeGeneratorExtensions
    {
        /// <summary>
        /// Appends a blank line if the previous line ended with a closing brace.
        /// </summary>
        /// <param name="generator">The generator to which to append the separator line.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendSeparatorLine(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            if ((generator.ScopeType == ScopeType.Type &&
                    generator.EndsWith($";\n")) ||
                    generator.EndsWith("}\n") ||
                    generator.EndsWith("#endif\n") ||
                    generator.EndsWith(";\r\n") ||
                    generator.EndsWith("}\r\n") ||
                    generator.EndsWith("#endif\r\n"))
            {
                // Append a blank line
                generator.AppendLine();
            }

            return generator;
        }

        /// <summary>
        /// Emits the auto-generated header.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendAutoGeneratedHeader(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .AppendBlockIndent(
                """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """);
        }

        /// <summary>
        /// Append using statements for the given namespaces.
        /// </summary>
        /// <param name="generator">The generator to which to append usings.</param>
        /// <param name="namespaces">The namespace to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendUsings(this CodeGenerator generator, params ConditionalCodeSpecification[] namespaces)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            ConditionalCodeSpecification.AppendConditionalsInOrder(
                generator,
                namespaces,
                static (g, a, _) => Append(g, a));

            return generator;

            static void Append(CodeGenerator generator, Action<CodeGenerator> action)
            {
                generator.Append("using ");
                action(generator);
                generator.AppendLine(";");
            }
        }

        /// <summary>
        /// Append the text as paragraphs, splitting on newline and/or carriage return.
        /// </summary>
        /// <param name="generator">The generator to which to append the paragraphs.</param>
        /// <param name="paragraphs">The text containing the paragraphs to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendParagraphs(this CodeGenerator generator, string paragraphs)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(paragraphs, removeBlankLines: true);
            foreach (string line in lines)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                generator
                    .AppendLineIndent("/// <para>")
                    .AppendIndent("/// ")
                    .AppendLine(SymbolDisplay.FormatLiteral(HttpUtility.HtmlEncode(line), false))
                    .AppendLineIndent("/// </para>");
            }

            return generator;
        }

        /// <summary>
        /// Append a multi-line block of text at the given indent.
        /// </summary>
        /// <param name="generator">The generator to which to append the block.</param>
        /// <param name="block">The block to append.</param>
        /// <param name="trimWhitespaceOnlyLines">Whether to trim lines that are whitespace only.</param>
        /// <param name="omitLastLineEnd">If <see langword="true"/> then the last line is appended without an additional line-end, leaving
        /// the generator at the end of the block.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendBlockIndent(this CodeGenerator generator, string block, bool trimWhitespaceOnlyLines = true, bool omitLastLineEnd = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(block);

            for (int i = 0; i < lines.Length; i++)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                string line = lines[i];
                if (omitLastLineEnd && i == lines.Length - 1)
                {
                    generator
                        .AppendIndent(line);
                }
                else
                {
                    generator
                        .AppendLineIndent(line, trimWhitespaceOnlyLines);
                }
            }

            return generator;
        }

        /// <summary>
        /// Append a multi-line block of text at the given indent.
        /// </summary>
        /// <param name="generator">The generator to which to append the block.</param>
        /// <param name="block">The block to append.</param>
        /// <param name="trimWhitespaceOnlyLines">Whether to trim lines that are whitespace only.</param>
        /// <param name="omitLastLineEnd">If <see langword="true"/> then the last line is appended without an additional line-end, leaving
        /// the generator at the end of the block.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendBlockIndentWithHashOutdent(this CodeGenerator generator, string block, bool trimWhitespaceOnlyLines = true, bool omitLastLineEnd = false)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(block);

            for (int i = 0; i < lines.Length; i++)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                string line = lines[i];
                if (omitLastLineEnd && i == lines.Length - 1)
                {
                    if (line[0] == '#')
                    {
                        generator.Append(line);
                    }
                    else
                    {
                        generator
                            .AppendIndent(line);
                    }
                }
                else
                {
                    if (line.Length > 0 && line[0] == '#')
                    {
                        generator.AppendLine(line);
                    }
                    else
                    {
                        generator
                            .AppendLineIndent(line, trimWhitespaceOnlyLines);
                    }
                }
            }

            return generator;
        }

        /// <summary>
        /// Append a multi-line block of text at the given indent, with a given line prefix.
        /// </summary>
        /// <param name="generator">The generator to which to append the block.</param>
        /// <param name="block">The block to append.</param>
        /// <param name="linePrefix">The prefix for each line.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendBlockIndentWithPrefix(this CodeGenerator generator, string block, string linePrefix)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string[] lines = NormalizeAndSplitBlockIntoLines(block);
            foreach (string line in lines)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                generator
                    .AppendIndent(linePrefix)
                    .AppendLine(line);
            }

            return generator;
        }

        /// <summary>
        /// Emits the parent/child nesting.
        /// </summary>
        /// <param name="generator">The generator to which to append the parent/child declaration nesting.</param>
        /// <param name="typeDeclaration">The type declaration being emitted.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginTypeDeclarationNesting(
            this CodeGenerator generator,
            TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            Stack<TypeDeclaration> parentTypes = new();

            TypeDeclaration? current = typeDeclaration.Parent();

            // We need to reverse the order, so we push them onto a stack...
            while (current is not null)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                parentTypes.Push(current);
                current = current.Parent();
            }

            bool isFirst = true;

            // Just begin our namespace if we have no parents.
            if (parentTypes.Count == 0)
            {
                return generator
                    .BeginNamespace(typeDeclaration.DotnetNamespace());
            }

            // ...and then pop them off again.
            while (parentTypes.Count > 0)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                TypeDeclaration parent = parentTypes.Pop();

                if (isFirst)
                {
                    generator
                        .BeginNamespace(parent.DotnetNamespace());
                    isFirst = false;
                }

                generator
                    .AppendSeparatorLine()
                    .AppendDocumentation(parent)
                    .BeginReadonlyPartialStructDeclaration(
                        parent.DotnetAccessibility(),
                        parent.DotnetTypeName());
            }

            return generator;
        }

        /// <summary>
        /// Closes off the parent/child nesting.
        /// </summary>
        /// <param name="generator">The generator to which to append the nested-type closing.</param>
        /// <param name="typeDeclaration">The type declaration being emitted.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator EndTypeDeclarationNesting(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            TypeDeclaration? current = typeDeclaration.Parent();
            while (current is not null)
            {
                if (generator.IsCancellationRequested)
                {
                    return generator;
                }

                generator.EndClassOrStructDeclaration();
                current = current.Parent();
            }

            return generator;
        }

        /// <summary>
        /// Append a namespace statement.
        /// </summary>
        /// <param name="generator">The generator to which to append usings.</param>
        /// <param name="ns">The namespace to append.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginNamespace(this CodeGenerator generator, string ns)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .Append("namespace ")
                .Append(ns)
                .AppendLine(";")
                .PushMemberScope(ns, ScopeType.TypeContainer);
        }

        /// <summary>
        /// Append a namespace statement.
        /// </summary>
        /// <param name="generator">The generator to which to append usings.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator EndNamespace(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .PopMemberScope();
        }

        /// <summary>
        /// Emits the start of a partial struct declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the beginning of the struct declaration.</param>
        /// <param name="accessibility">The accessibility for the generated type.</param>
        /// <param name="dotnetTypeName">The .NET type name for the partial struct.</param>
        /// <param name="interfaces">Interfaces to implement.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator BeginReadonlyPartialStructDeclaration(
            this CodeGenerator generator,
            GeneratedTypeAccessibility accessibility,
            string dotnetTypeName,
            ConditionalCodeSpecification[]? interfaces = null)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            string accessibilityString = accessibility switch
            {
                GeneratedTypeAccessibility.Public => "public",
                GeneratedTypeAccessibility.Internal => "internal",
                _ => throw new ArgumentOutOfRangeException(nameof(accessibility)),
            };

            generator.ReserveNameIfNotReserved(dotnetTypeName);
            generator
                .AppendIndent(accessibilityString, " readonly partial struct ")
                .AppendLine(dotnetTypeName);

            if (interfaces is ConditionalCodeSpecification[] conditionalSpecifications)
            {
                generator.PushIndent();
                ConditionalCodeSpecification.AppendConditionalsGroupingBlocks(generator, conditionalSpecifications, AppendInterface);
                generator.PopIndent();
            }

            return generator
                .AppendLineIndent("{")
                .PushMemberScope(dotnetTypeName, ScopeType.Type)
                .ReserveNameIfNotReserved(dotnetTypeName) // Reserve the name of the containing scope in its own scope
                .PushIndent();

            static void AppendInterface(CodeGenerator generator, Action<CodeGenerator> appendFunction, int elementIndexInConditionalBlock)
            {
                if (generator.IsCancellationRequested)
                {
                    return;
                }

                if (elementIndexInConditionalBlock == 0)
                {
                    generator.AppendIndent(": ");
                    appendFunction(generator);
                }
                else
                {
                    generator
                        .AppendLine(",")
                        .AppendIndent("  "); // Align with the ": "
                    appendFunction(generator);
                }
            }
        }

        /// <summary>
        /// Emits the end of a class or struct declaration.
        /// </summary>
        /// <param name="generator">The generator to which to append the end of the struct declaration.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator EndClassOrStructDeclaration(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .PopMemberScope()
                .PopIndent()
                .AppendLineIndent("}");
        }

        public static CodeGenerator AppendBackingFields(this CodeGenerator generator)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .AppendLineIndent("private readonly IJsonDocument _parent;")
                .AppendLineIndent("private readonly int _idx;");
        }

        /// <summary>
        /// Append the default constructor for the type declaration.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the constructor.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendInternalConstructor(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            CoreTypes impliedCoreTypes = typeDeclaration.ImpliedCoreTypesOrAny();

            return generator
                .AppendSeparatorLine()
                .AppendLineIndent("/// <summary>")
                .AppendIndent("/// Initializes a new instance of the ")
                .AppendTypeAsSeeCref(typeDeclaration.DotnetTypeName())
                .AppendLine(" struct.")
                .AppendLineIndent("/// </summary>")
                .AppendLineIndent("/// <param name=\"value\">The value from which to construct the instance.</param>")
                .AppendIndent("internal ")
                .Append(typeDeclaration.DotnetTypeName())
                .AppendLine("(IJsonDocument parent, int idx)")
                .AppendLineIndent("{")
                .PushIndent()
                    .AppendLine("Debug.Assert(idx >= 0);")
                    .AppendLine("_parent = parent;")
                    .AppendLine("_idx = idx;")
                .PopIndent()
                .AppendLineIndent("}");
        }

        /// <summary>
        /// Append the schema location static property for the type declaration.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the property.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendSchemaLocationStaticProperty(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("SchemaLocation")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                """
            /// <summary>
            /// Gets the schema location from which this type was generated.
            /// </summary>
            """)
                .AppendIndent("public static string SchemaLocation { get; } = ")
                .Append(SymbolDisplay.FormatLiteral(typeDeclaration.RelativeSchemaLocation, true))
                .AppendLine(";");
        }

        /// <summary>
        /// Append the static property which provides a default instance of the type declaration.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the property.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendDefaultInstanceStaticProperty(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .ReserveName("DefaultInstance")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                """
            /// <summary>
            /// Gets the default instance.
            /// </summary>
            """)
                .AppendIndent("public static ")
                .Append(typeDeclaration.DotnetTypeName())
                .Append(" DefaultInstance { get; }");

            return typeDeclaration.DefaultValue().ValueKind switch
            {
                JsonValueKind.Undefined => generator.AppendLine(),
                JsonValueKind.Null => generator
                                        .Append(" = ")
                                        .Append(typeDeclaration.DotnetTypeName())
                                        .AppendLine(".ParseValue(\"null\"u8);"),
                _ => generator
                        .Append(" = ")
                        .Append(typeDeclaration.DotnetTypeName())
                        .Append(".ParseValue(")
                        .Append(SymbolDisplay.FormatLiteral(typeDeclaration.DefaultValue().GetRawText(), true))
                        .AppendLine("u8);"),
            };
        }

        /// <summary>
        /// Append a property which gets the <see cref="JsonValueKind"/> for the instance.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the property.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendValueKindProperty(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("ValueKind")
                .AppendSeparatorLine()
                .AppendLineIndent("/// <inheritdoc/>")
                .AppendLineIndent("public JsonValueKind ValueKind => TokenType.ToValueKind();");
        }

        /// <summary>
        /// Append a property which gets the <c>JsonTokenType</c> for the instance.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to emit the property.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendTokenTypeProperty(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("TokenType")
                .AppendSeparatorLine()
                .AppendLineIndent("[DebuggerBrowsable(DebuggerBrowsableState.Never)]")
                .AppendLineIndent("private JsonTokenType TokenType => _parent?.GetJsonTokenType(_idx) ?? JsonTokenType.None;");
        }

        /// <summary>
        /// Appends the From static factory method.
        /// to JsonAny.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration to which to convert.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendFromFactoryMethod(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
                .ReserveName("FromJson")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <summary>
                    /// Gets an instance of the JSON value from another element.
                    /// </summary>
                    /// <param name="value">The <see cref="IJsonElement{T}"/> value from which to instantiate the instance.</param>
                    /// <returns>An instance of this type, initialized from the <see cref="IJsonElement{T}"/>.</returns>                
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    """)
                .AppendIndent("public static ", typeDeclaration.DotnetTypeName()," From<T>(in T instance)")
                .PushIndent()
                    .AppendLine("where T : struct, IJsonElement<T>")
                .PopIndent()
                .AppendLineIndent("{")
                .PushIndent()
                    .AppendLineIndent("return new(instance.ParentDocument, instance.ParentDocumentIndex);")
                .PopIndent()
                .AppendLineIndent("}");
        }


        /// <summary>
        /// Append the Equals() method overloads.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to produce the methods.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendEqualsOverloads(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .ReserveNameIfNotReserved("Equals")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <inheritdoc/>
                    public override bool Equals(object? obj)
                    {
                        return
                    """)
                .PushIndent()
                .PushIndent()
                .AppendLineIndent("(obj is IJsonElement value && this.Equals(new ", typeDeclaration.DotnetTypeName(), "(value.ParentDocument, value.ParentDocumentIndex))) ||")
                .PopIndent()
                .PopIndent()
                .AppendBlockIndent(
                    """
                            (obj is null && this.IsNull());
                    }

                    /// <inheritdoc/>
                    public bool Equals<T>(in T other)
                        where T : struct, IJsonValue<T>
                    {
                    """)
                .PushIndent()
                .AppendLineIndent("return this.Equals(other.As<", typeDeclaration.DotnetTypeName(), ">());")
                .PopIndent()
                .AppendLineIndent("}")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <summary>
                    /// Equality comparison.
                    /// </summary>
                    /// <param name="other">The other item with which to compare.</param>
                    /// <returns><see langword="true"/> if the values were equal.</returns>
                    """)
                .AppendIndent("public bool Equals<T>(in T other)")
                .PushIndent()
                    .AppendIndent("where T : struct, IJsonElement")
                .PopIndent()
                .AppendLineIndent("{")
                .PushIndent();

            bool appendDefault = true;
            if (typeDeclaration.Format() is string format)
            {
                appendDefault = !FormatHandlerRegistry.Instance.FormatHandlers.AppendFormatEqualsTBody(generator, typeDeclaration, format);
            }

            if (appendDefault)
            {
                generator
                    .AppendLineIndent("return JsonElementHelpers.DeepEquals(this, other);");
            }

            return generator
                .PopIndent()
                .AppendLineIndent("}");
        }

        /// <summary>
        /// Append the WriteTo() method.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to produce the method.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendWriteToMethod(this CodeGenerator generator, TypeDeclaration typeDeclaration)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            return generator
            .ReserveName("WriteTo")
            .AppendSeparatorLine()
            .AppendLineIndent("/// <inheritdoc/>")
            .AppendLineIndent("public void WriteTo(Utf8JsonWriter writer)")
            .AppendLineIndent("{")
            .PushIndent()
                .AppendLineIndent("CheckValidInstance();")
                .AppendLineIndent("_parent.WriteElementTo(_idx, writer);")
            .PopIndent()
            .AppendLineIndent("}");
        }

        /// <summary>
        /// Appends the GetHashCode() and ToString() methods.
        /// </summary>
        /// <param name="generator">The code generator.</param>
        /// <param name="typeDeclaration">The type declaration for which to append the methods.</param>
        /// <returns>A reference to the generator having completed the operation.</returns>
        public static CodeGenerator AppendGetHashCodeAndToStringMethods(this CodeGenerator generator, TypeDeclaration typeDeclaration, bool forMutable)
        {
            if (generator.IsCancellationRequested)
            {
                return generator;
            }

            generator
                .ReserveNameIfNotReserved("GetHashCode")
                .ReserveNameIfNotReserved("ToString")
                .AppendSeparatorLine()
                .AppendBlockIndent(
                    """
                    /// <inheritdoc/>
                    public override int GetHashCode()
                    {
                        if (_parent == null)
                        {
                            return 0;
                        }

                        return _parent.GetHashCode(_idx);
                    }
                    """)
                .AppendSeparatorLine();


            if (forMutable)
            {
                return generator
                    .AppendBlockIndent(
                        """
                        /// <inheritdoc/>
                        public override string ToString()
                        {
                            if (_parent == null || _documentVersion != _parent.Version)
                            {
                                return string.Empty;
                            }

                            return _parent.ToString(_idx);
                        }
                        """);
            }
            else
            {
                return generator
                    .AppendBlockIndent(
                        """
                        /// <inheritdoc/>
                        public override string ToString()
                        {
                            if (_parent is null)
                            {
                                return string.Empty;
                            }

                            return _parent.ToString(_idx);
                        }
                        """);
            }
        }

        private static string[] NormalizeAndSplitBlockIntoLines(string block, bool removeBlankLines = false)
        {
            string normalizedBlock = block.Replace("\r\n", "\n");
            string[] lines = normalizedBlock.Split(['\n'], removeBlankLines ? StringSplitOptions.RemoveEmptyEntries : StringSplitOptions.None);
            return lines;
        }
    }
}
