// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Source files represent a source generated JsonSerializerContext as produced by the .NET 7 SDK.
// Used to validate correctness of contexts generated by previous SDKs against the current Corvus.Text.Json runtime components.
// Unless absolutely necessary DO NOT MODIFY any of these files -- it would invalidate the purpose of the regression tests.

// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70
{
    public partial class Net70GeneratedContext
    {
        
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_Date = global::Corvus.Text.Json.JsonEncodedText.Encode("Date");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_TemperatureCelsius = global::Corvus.Text.Json.JsonEncodedText.Encode("TemperatureCelsius");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_Summary = global::Corvus.Text.Json.JsonEncodedText.Encode("Summary");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_DatesAvailable = global::Corvus.Text.Json.JsonEncodedText.Encode("DatesAvailable");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_TemperatureRanges = global::Corvus.Text.Json.JsonEncodedText.Encode("TemperatureRanges");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_SummaryWords = global::Corvus.Text.Json.JsonEncodedText.Encode("SummaryWords");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_High = global::Corvus.Text.Json.JsonEncodedText.Encode("High");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_Low = global::Corvus.Text.Json.JsonEncodedText.Encode("Low");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_Value = global::Corvus.Text.Json.JsonEncodedText.Encode("Value");
        private static readonly global::Corvus.Text.Json.JsonEncodedText PropName_Nested = global::Corvus.Text.Json.JsonEncodedText.Encode("Nested");
    }
}
