// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Source files represent a source generated JsonSerializerContext as produced by the .NET 7 SDK.
// Used to validate correctness of contexts generated by previous SDKs against the current Corvus.Text.Json runtime components.
// Unless absolutely necessary DO NOT MODIFY any of these files -- it would invalidate the purpose of the regression tests.

// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70
{
    public partial class Net70GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList>? _MyLinkedList;
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList> MyLinkedList
        {
            get => _MyLinkedList ??= Create_MyLinkedList(Options, makeReadOnly: true);
        }

        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList> Create_MyLinkedList(global::Corvus.Text.Json.JsonSerializerOptions options, bool makeReadOnly)
        {
            global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList>? jsonTypeInfo = null;
            global::Corvus.Text.Json.Serialization.JsonConverter? customConverter;
            if (options.Converters.Count > 0 && (customConverter = GetRuntimeProvidedCustomConverter(options, typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList))) != null)
            {
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList>(options, customConverter);
            }
            else
            {
                global::Corvus.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList> objectInfo = new global::Corvus.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList>()
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static (args) => new global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList((global::System.Int32)args[0], (global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList)args[1]),
                    PropertyMetadataInitializer = _ => MyLinkedListPropInit(options),
                    ConstructorParameterMetadataInitializer = MyLinkedListCtorParamInit,
                    NumberHandling = default,
                    SerializeHandler = MyLinkedListSerializeHandler
                };

                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList>(options, objectInfo);
            }

            if (makeReadOnly)
            {
                jsonTypeInfo.MakeReadOnly();
            }

            return jsonTypeInfo;
        }

        private static global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[] MyLinkedListPropInit(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[] properties = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[2];

            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Int32> info0 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Int32>()
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList),
                Converter = null,
                Getter = static (obj) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList)obj).Value,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList)obj).Value = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = default,
                PropertyName = "Value",
                JsonPropertyName = null
            };

            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo propertyInfo0 = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Int32>(options, info0);
            properties[0] = propertyInfo0;

            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList> info1 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList>()
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList),
                Converter = null,
                Getter = static (obj) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList)obj).Nested!,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList)obj).Nested = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = default,
                PropertyName = "Nested",
                JsonPropertyName = null
            };

            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo propertyInfo1 = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList>(options, info1);
            properties[1] = propertyInfo1;

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void MyLinkedListSerializeHandler(global::Corvus.Text.Json.Utf8JsonWriter writer, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }

            writer.WriteStartObject();
            writer.WriteNumber(PropName_Value, value.Value);
            writer.WritePropertyName(PropName_Nested);
            MyLinkedListSerializeHandler(writer, value.Nested!);

            writer.WriteEndObject();
        }

        private static global::Corvus.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] MyLinkedListCtorParamInit()
        {
            global::Corvus.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] parameters = new global::Corvus.Text.Json.Serialization.Metadata.JsonParameterInfoValues[2];
            global::Corvus.Text.Json.Serialization.Metadata.JsonParameterInfoValues info;

            info = new()
            {
                Name = "value",
                ParameterType = typeof(global::System.Int32),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(global::System.Int32)
            };
            parameters[0] = info;

            info = new()
            {
                Name = "nested",
                ParameterType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.MyLinkedList)
            };
            parameters[1] = info;

            return parameters;
        }
    }
}
