// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Source files represent a source generated JsonSerializerContext as produced by the .NET 7 SDK.
// Used to validate correctness of contexts generated by previous SDKs against the current Corvus.Text.Json runtime components.
// Unless absolutely necessary DO NOT MODIFY any of these files -- it would invalidate the purpose of the regression tests.

// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70
{
    public partial class Net70GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter>? _ClassWithCustomConverter;
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter> ClassWithCustomConverter
        {
            get => _ClassWithCustomConverter ??= Create_ClassWithCustomConverter(Options, makeReadOnly: true);
        }
        
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter> Create_ClassWithCustomConverter(global::Corvus.Text.Json.JsonSerializerOptions options, bool makeReadOnly)
        {
            global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter>? jsonTypeInfo = null;
            global::Corvus.Text.Json.Serialization.JsonConverter? customConverter;
            if (options.Converters.Count > 0 && (customConverter = GetRuntimeProvidedCustomConverter(options, typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter))) != null)
            {
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter>(options, customConverter);
            }
            else
            {
                global::Corvus.Text.Json.Serialization.JsonConverter converter = new global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter.CustomConverter();
                        global::System.Type typeToConvert = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter);
                        if (!converter.CanConvert(typeToConvert))
                        {
                            throw new global::System.InvalidOperationException(string.Format("The converter '{0}' is not compatible with the type '{1}'.", converter.GetType(), typeToConvert));
                        }
                        jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net70.ClassWithCustomConverter> (options, converter); 
            }
        
            if (makeReadOnly)
            {
                jsonTypeInfo.MakeReadOnly();
            }
        
            return jsonTypeInfo;
        }
        
    }
}
