// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Source files represent a source generated JsonSerializerContext as produced by the .NET 8 SDK.
// Used to validate correctness of contexts generated by previous SDKs against the current Corvus.Text.Json runtime components.
// Unless absolutely necessary DO NOT MODIFY any of these files -- it would invalidate the purpose of the regression tests.

// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80
{
    public partial class Net80GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps>? _HighLowTemps;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps> HighLowTemps
        {
            get => _HighLowTemps ??= (global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps>)Options.GetTypeInfo(typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps));
        }
        
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps> Create_HighLowTemps(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps>(options, out global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps> jsonTypeInfo))
            {
                var objectInfo = new global::Corvus.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps>
                {
                    ObjectCreator = () => new global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps(),
                    ObjectWithParameterizedConstructorCreator = null,
                    PropertyMetadataInitializer = _ => HighLowTempsPropInit(options),
                    ConstructorParameterMetadataInitializer = null,
                    SerializeHandler = HighLowTempsSerializeHandler
                };
                
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[] HighLowTempsPropInit(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[2];

            var info0 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps),
                Converter = null,
                Getter = static obj => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps)obj).High,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps)obj).High = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "High",
                JsonPropertyName = null
            };
            
            properties[0] = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info0);

            var info1 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps),
                Converter = null,
                Getter = static obj => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps)obj).Low,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps)obj).Low = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Low",
                JsonPropertyName = null
            };
            
            properties[1] = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info1);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void HighLowTempsSerializeHandler(global::Corvus.Text.Json.Utf8JsonWriter writer, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteNumber(PropName_High, ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps)value).High);
            writer.WriteNumber(PropName_Low, ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80.HighLowTemps)value).Low);

            writer.WriteEndObject();
        }
    }
}
