// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Source files represent a source generated JsonSerializerContext as produced by the .NET 8 SDK.
// Used to validate correctness of contexts generated by previous SDKs against the current Corvus.Text.Json runtime components.
// Unless absolutely necessary DO NOT MODIFY any of these files -- it would invalidate the purpose of the regression tests.

// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net80
{
    public partial class Net80GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.DateTimeOffset>>? _ListDateTimeOffset;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.DateTimeOffset>> ListDateTimeOffset
        {
            get => _ListDateTimeOffset ??= (global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.DateTimeOffset>>)Options.GetTypeInfo(typeof(global::System.Collections.Generic.List<global::System.DateTimeOffset>));
        }
        
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.DateTimeOffset>> Create_ListDateTimeOffset(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.Collections.Generic.List<global::System.DateTimeOffset>>(options, out global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.DateTimeOffset>> jsonTypeInfo))
            {
                var info = new global::Corvus.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::System.Collections.Generic.List<global::System.DateTimeOffset>>
                {
                    ObjectCreator = () => new global::System.Collections.Generic.List<global::System.DateTimeOffset>(),
                    SerializeHandler = ListDateTimeOffsetSerializeHandler
                };
                
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateListInfo<global::System.Collections.Generic.List<global::System.DateTimeOffset>, global::System.DateTimeOffset>(options, info);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void ListDateTimeOffsetSerializeHandler(global::Corvus.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.List<global::System.DateTimeOffset>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartArray();

            for (int i = 0; i < value.Count; i++)
            {
                writer.WriteStringValue(value[i]);
            }

            writer.WriteEndArray();
        }
    }
}
