// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Source files represent a source generated JsonSerializerContext as produced by the .NET 6 SDK.
// Used to validate correctness of contexts generated by previous SDKs against the current Corvus.Text.Json runtime components.
// Unless absolutely necessary DO NOT MODIFY any of these files -- it would invalidate the purpose of the regression tests.

// <auto-generated/>
#nullable enable

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60
{
    public partial class Net60GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps>? _HighLowTemps;
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps> HighLowTemps
        {
            get
            {
                if (_HighLowTemps == null)
                {
                    global::Corvus.Text.Json.Serialization.JsonConverter? customConverter;
                    if (Options.Converters.Count > 0 && (customConverter = GetRuntimeProvidedCustomConverter(typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps))) != null)
                    {
                        _HighLowTemps = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps>(Options, customConverter);
                    }
                    else
                    {
                        global::Corvus.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps> objectInfo = new global::Corvus.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps>()
                        {
                            ObjectCreator = static () => new global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps(),
                            ObjectWithParameterizedConstructorCreator = null,
                            PropertyMetadataInitializer = HighLowTempsPropInit,
                            ConstructorParameterMetadataInitializer = null,
                            NumberHandling = default,
                            SerializeHandler = HighLowTempsSerializeHandler
                        };
            
                        _HighLowTemps = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps>(Options, objectInfo);
                    }
                }
        
                return _HighLowTemps;
            }
        }
        
        private static global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[] HighLowTempsPropInit(global::Corvus.Text.Json.Serialization.JsonSerializerContext context)
        {
            global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.Net60GeneratedContext jsonContext = (global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.Net60GeneratedContext)context;
            global::Corvus.Text.Json.JsonSerializerOptions options = context.Options;
        
            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[] properties = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[2];
        
            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Int32> info0 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Int32>()
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps),
                PropertyTypeInfo = jsonContext.Int32,
                Converter = null,
                Getter = static (obj) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps)obj).High,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps)obj).High = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = default,
                PropertyName = "High",
                JsonPropertyName = null
            };
        
            properties[0] = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Int32>(options, info0);
            
            global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Int32> info1 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Int32>()
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps),
                PropertyTypeInfo = jsonContext.Int32,
                Converter = null,
                Getter = static (obj) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps)obj).Low,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps)obj).Low = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = default,
                PropertyName = "Low",
                JsonPropertyName = null
            };
        
            properties[1] = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Int32>(options, info1);
            
            return properties;
        }
        
        private static void HighLowTempsSerializeHandler(global::Corvus.Text.Json.Utf8JsonWriter writer, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.HighLowTemps? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
        
            writer.WriteStartObject();
            writer.WriteNumber(PropName_High, value.High);
            writer.WriteNumber(PropName_Low, value.Low);
        
            writer.WriteEndObject();
        }
    }
}
