// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Source files represent a source generated JsonSerializerContext as produced by the .NET 6 SDK.
// Used to validate correctness of contexts generated by previous SDKs against the current Corvus.Text.Json runtime components.
// Unless absolutely necessary DO NOT MODIFY any of these files -- it would invalidate the purpose of the regression tests.

// <auto-generated/>
#nullable enable

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60
{
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Corvus.Text.Json.SourceGeneration", "6.0.8.17311")]
    public partial class Net60GeneratedContext
    {
        
        private static global::Corvus.Text.Json.JsonSerializerOptions s_defaultOptions { get; } = new global::Corvus.Text.Json.JsonSerializerOptions()
        {
            DefaultIgnoreCondition = global::Corvus.Text.Json.Serialization.JsonIgnoreCondition.Never,
            IgnoreReadOnlyFields = false,
            IgnoreReadOnlyProperties = false,
            IncludeFields = false,
            WriteIndented = false,
        };
        
        private static global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.Net60GeneratedContext? s_defaultContext;
        public static global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.Net60GeneratedContext Default => s_defaultContext ??= new global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net60.Net60GeneratedContext(new global::Corvus.Text.Json.JsonSerializerOptions(s_defaultOptions));
        
        protected override global::Corvus.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions { get; } = s_defaultOptions;
        
        public Net60GeneratedContext() : base(null)
        {
        }
        
        public Net60GeneratedContext(global::Corvus.Text.Json.JsonSerializerOptions options) : base(options)
        {
        }
        
        private global::Corvus.Text.Json.Serialization.JsonConverter? GetRuntimeProvidedCustomConverter(global::System.Type type)
        {
            global::System.Collections.Generic.IList<global::Corvus.Text.Json.Serialization.JsonConverter> converters = Options.Converters;
        
            for (int i = 0; i < converters.Count; i++)
            {
                global::Corvus.Text.Json.Serialization.JsonConverter? converter = converters[i];
        
                if (converter.CanConvert(type))
                {
                    if (converter is global::Corvus.Text.Json.Serialization.JsonConverterFactory factory)
                    {
                        converter = factory.CreateConverter(type, Options);
                        if (converter == null || converter is global::Corvus.Text.Json.Serialization.JsonConverterFactory)
                        {
                            throw new global::System.InvalidOperationException(string.Format("The converter '{0}' cannot return null or a JsonConverterFactory instance.", factory.GetType()));
                        }
                    }
        
                    return converter;
                }
            }
        
            return null;
        }
    }
}
