// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

#if NET
using System.Runtime.Loader;
#endif

using System.Threading;
using System.Threading.Tasks;
using Corvus.Json;
using Corvus.Json.CodeGeneration;
using Corvus.Json.CodeGeneration.DocumentResolvers;
using Corvus.Text.Json;
using Corvus.Text.Json.CodeGeneration;
using Corvus.Text.Json.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyModel;
using NodaTime;

namespace TestUtilities
{
    public class TestJsonSchemaCodeGenerator
    {
        private static readonly ConcurrentDictionary<string, DynamicJsonType> s_compiledTypesCache = new();
#if NET
        private readonly TestAssemblyLoadContext _assemblyLoadContext = new();
#endif
        private readonly IDocumentResolver _documentResolver;
        private readonly VocabularyRegistry _vocabularyRegistry;
        private readonly JsonSchemaTypeBuilder _jsonSchemaTypeBuilder;
        private readonly IVocabulary _defaultVocabulary;
        private readonly string? _remotesBaseDirectory;
        private readonly bool _validateFormat;
        private readonly bool _optionalAsNullable;
        private readonly bool _useImplicitOperatorString;
        private readonly bool _addExplicitUsings;

        private const string GlobalUsingStatements =
        """
        // <auto-generated/>
        global using global::System;
        global using global::System.Collections.Generic;
        global using global::System.Diagnostics;
        global using global::System.Diagnostics.CodeAnalysis;
        global using global::System.IO;
        global using global::System.Linq;
        """;

        private TestJsonSchemaCodeGenerator(
            string remotesBaseDirectory,
            IVocabulary? defaultVocabulary = null,
            bool validateFormat = true,
            bool optionalAsNullable = false,
            bool useImplicitOperatorString = false,
            bool addExplicitUsings = true)
            : this(remotesBaseDirectory, null, defaultVocabulary, validateFormat, optionalAsNullable, useImplicitOperatorString, addExplicitUsings)
        {
        }

        private TestJsonSchemaCodeGenerator(
            string remotesBaseDirectory,
            IDocumentResolver? resolver,
            IVocabulary? defaultVocabulary = null,
            bool validateFormat = true,
            bool optionalAsNullable = false,
            bool useImplicitOperatorString = false,
            bool addExplicitUsings = true)
        {
            _remotesBaseDirectory = remotesBaseDirectory;
            _documentResolver =
                resolver?.AddMetaschema() ??
                new CompoundDocumentResolver(
                    new FakeWebDocumentResolver(_remotesBaseDirectory!),
                    new FileSystemDocumentResolver())
                        .AddMetaschema();

            _vocabularyRegistry = new();
            Corvus.Json.CodeGeneration.Draft202012.VocabularyAnalyser.RegisterAnalyser(_documentResolver, _vocabularyRegistry);
            Corvus.Json.CodeGeneration.Draft201909.VocabularyAnalyser.RegisterAnalyser(_documentResolver, _vocabularyRegistry);
            Corvus.Json.CodeGeneration.Draft7.VocabularyAnalyser.RegisterAnalyser(_vocabularyRegistry);
            Corvus.Json.CodeGeneration.Draft6.VocabularyAnalyser.RegisterAnalyser(_vocabularyRegistry);
            Corvus.Json.CodeGeneration.Draft4.VocabularyAnalyser.RegisterAnalyser(_vocabularyRegistry);
            Corvus.Json.CodeGeneration.OpenApi30.VocabularyAnalyser.RegisterAnalyser(_vocabularyRegistry);

            _jsonSchemaTypeBuilder = new(_documentResolver, _vocabularyRegistry);
            _defaultVocabulary = defaultVocabulary ?? Corvus.Json.CodeGeneration.Draft202012.VocabularyAnalyser.DefaultVocabulary;
            _validateFormat = validateFormat;
            _optionalAsNullable = optionalAsNullable;
            _useImplicitOperatorString = useImplicitOperatorString;
            _addExplicitUsings = addExplicitUsings;
        }

        /// <summary>
        /// Generate the JSON type for the given test suite entry.
        /// </summary>
        /// <param name="filename">The name of the test suite defintiion file.</param>
        /// <param name="schemaPath">The path to the schema in the test suite definition file.</param>
        /// <param name="testCaseName">The name of the test case.</param>
        /// <param name="remotesBaseDirectory">The remotes base directory for the test suite.</param>
        /// <param name="defaultVocabulary">The default vocabulary for the test run.</param>
        /// <param name="validateFormat">Whether to enforce format validation rather than just evaluation.</param>
        /// <param name="optionalAsNullable">Whether to treat optional as nullable.</param>
        /// <param name="useImplicitOperatorString">Whether to generate implicit conversions to string.</param>
        /// <param name="addExplicitUsings">Whether to add explicit usings for the generated code, or rely on the global usings.</param>
        /// <param name="hostAssembly">The host assembly with preserved compilation context.</param>
        /// <returns></returns>

        public static async ValueTask<DynamicJsonType> GenerateTypeForJsonSchemaTestSuite(
            string filename,
            string schemaPath,
            string testCaseName,
            string remotesBaseDirectory,
            IVocabulary defaultVocabulary,
            bool validateFormat,
            bool optionalAsNullable,
            bool useImplicitOperatorString,
            bool addExplicitUsings,
            Assembly hostAssembly)
        {
            string key = filename + schemaPath;
            if (s_compiledTypesCache.TryGetValue(key, out DynamicJsonType value))
            {
                return value;
            }

            // Potentially execute async operation unnecessarily, but only in the case where we need to add to the cache.
            var generator = new TestJsonSchemaCodeGenerator(
                remotesBaseDirectory,
                defaultVocabulary: defaultVocabulary,
                validateFormat: validateFormat,
                optionalAsNullable: optionalAsNullable,
                useImplicitOperatorString: useImplicitOperatorString,
                addExplicitUsings: addExplicitUsings);


#if NET
            string text = await File.ReadAllTextAsync(filename);
#else
            string text = File.ReadAllText(filename);
#endif
            GeneratedCode generatedCode = await generator.GenerateCodeAsync(schemaPath, text, defaultNamespace: ToPascalCase(testCaseName));
            DynamicJsonType result = generator.Compile(generatedCode, hostAssembly);
            return s_compiledTypesCache.GetOrAdd(key, _ => result);
        }

        /// <summary>
        /// Generate the JSON type for the given test suite entry.
        /// </summary>
        /// <param name="virtualFilename">The virtual file name.</param>
        /// <param name="schemaText">The text of the virtual schema file.</param>
        /// <param name="testCaseName">The name of the test case.</param>
        /// <param name="remotesBaseDirectory">The remotes base directory for the test suite.</param>
        /// <param name="defaultVocabulary">The default vocabulary for the test run.</param>
        /// <param name="validateFormat">Whether to enforce format validation rather than just evaluation.</param>
        /// <param name="optionalAsNullable">Whether to treat optional as nullable.</param>
        /// <param name="useImplicitOperatorString">Whether to generate implicit conversions to string.</param>
        /// <param name="addExplicitUsings">Whether to add explicit usings for the generated code, or rely on the global usings.</param>
        /// <param name="hostAssembly">The host assembly with preserved compilation context.</param>
        /// <returns></returns>
        public static async ValueTask<DynamicJsonType> GenerateTypeForVirtualFile(
            string virtualFilename,
            string schemaText,
            string testCaseName,
            string remotesBaseDirectory,
            IVocabulary defaultVocabulary,
            bool validateFormat,
            bool optionalAsNullable,
            bool useImplicitOperatorString,
            bool addExplicitUsings,
            Assembly hostAssembly)
        {
            string key = schemaText;
            if (s_compiledTypesCache.TryGetValue(key, out DynamicJsonType value))
            {
                return value;
            }

            // Potentially execute async operation unnecessarily, but only in the case where we need to add to the cache.
            var generator = new TestJsonSchemaCodeGenerator(
                remotesBaseDirectory,
                defaultVocabulary: defaultVocabulary,
                validateFormat: validateFormat,
                optionalAsNullable: optionalAsNullable,
                useImplicitOperatorString: useImplicitOperatorString,
                addExplicitUsings: addExplicitUsings);


            GeneratedCode generatedCode = await generator.GenerateCodeAsync(virtualFilename, schemaText, defaultNamespace: ToPascalCase(testCaseName));
            DynamicJsonType result = generator.Compile(generatedCode, hostAssembly);
            return s_compiledTypesCache.GetOrAdd(key, _ => result);
        }


        /// <summary>
        /// Generate the JSON type for the given test suite entry.
        /// </summary>
        /// <param name="filename">The name of the test suite defintiion file.</param>
        /// <param name="schemaPath">The path to the schema in the test suite definition file.</param>
        /// <param name="testCaseName">The name of the test case.</param>
        /// <param name="remotesBaseDirectory">The remotes base directory for the test suite.</param>
        /// <param name="defaultVocabulary">The default vocabulary for the test run.</param>
        /// <param name="validateFormat">Whether to enforce format validation rather than just evaluation.</param>
        /// <param name="optionalAsNullable">Whether to treat optional as nullable.</param>
        /// <param name="useImplicitOperatorString">Whether to generate implicit conversions to string.</param>
        /// <param name="addExplicitUsings">Whether to add explicit usings for the generated code, or rely on the global usings.</param>
        /// <param name="hostAssembly">The host assembly with preserved compilation context.</param>
        /// <returns></returns>
        public static DynamicJsonType SynchronoulsyGenerateTypeForJsonSchemaTestSuite(
            string filename,
            string schemaPath,
            string testCaseName,
            string remotesBaseDirectory,
            IVocabulary defaultVocabulary,
            bool validateFormat,
            bool optionalAsNullable,
            bool useImplicitOperatorString,
            bool addExplicitUsings,
            Assembly hostAssembly)
        {
            string key = filename + schemaPath;
            if (s_compiledTypesCache.TryGetValue(key, out DynamicJsonType value))
            {
                return value;
            }

            // Potentially execute async operation unnecessarily, but only in the case where we need to add to the cache.
            var generator = new TestJsonSchemaCodeGenerator(
                remotesBaseDirectory,
                defaultVocabulary: defaultVocabulary,
                validateFormat: validateFormat,
                optionalAsNullable: optionalAsNullable,
                useImplicitOperatorString: useImplicitOperatorString,
                addExplicitUsings: addExplicitUsings);


            GeneratedCode generatedCode = generator.GenerateCodeSync(schemaPath, File.ReadAllText(filename), defaultNamespace: ToPascalCase(testCaseName));
            DynamicJsonType result = generator.Compile(generatedCode, hostAssembly);
            return s_compiledTypesCache.GetOrAdd(key, _ => result);
        }

        /// <summary>
        /// Generate the JSON type for the given test suite entry.
        /// </summary>
        /// <param name="virtualFilename">The virtual file name.</param>
        /// <param name="schemaText">The text of the virtual schema file.</param>
        /// <param name="testCaseName">The name of the test case.</param>
        /// <param name="remotesBaseDirectory">The remotes base directory for the test suite.</param>
        /// <param name="defaultVocabulary">The default vocabulary for the test run.</param>
        /// <param name="validateFormat">Whether to enforce format validation rather than just evaluation.</param>
        /// <param name="optionalAsNullable">Whether to treat optional as nullable.</param>
        /// <param name="useImplicitOperatorString">Whether to generate implicit conversions to string.</param>
        /// <param name="addExplicitUsings">Whether to add explicit usings for the generated code, or rely on the global usings.</param>
        /// <param name="hostAssembly">The host assembly with preserved compilation context.</param>
        /// <returns></returns>

        public static DynamicJsonType SynchronouslyGenerateTypeForVirtualFile(
            string virtualFilename,
            string schemaText,
            string testCaseName,
            string remotesBaseDirectory,
            IVocabulary defaultVocabulary,
            bool validateFormat,
            bool optionalAsNullable,
            bool useImplicitOperatorString,
            bool addExplicitUsings,
            Assembly hostAssembly)
        {
            string key = schemaText;
            if (s_compiledTypesCache.TryGetValue(key, out DynamicJsonType value))
            {
                return value;
            }

            // Potentially execute async operation unnecessarily, but only in the case where we need to add to the cache.
            var generator = new TestJsonSchemaCodeGenerator(
                remotesBaseDirectory,
                defaultVocabulary: defaultVocabulary,
                validateFormat: validateFormat,
                optionalAsNullable: optionalAsNullable,
                useImplicitOperatorString: useImplicitOperatorString,
                addExplicitUsings: addExplicitUsings);


            GeneratedCode generatedCode = generator.GenerateCodeSync(virtualFilename, schemaText, defaultNamespace: ToPascalCase(testCaseName));
            DynamicJsonType result = generator.Compile(generatedCode, hostAssembly);
            return s_compiledTypesCache.GetOrAdd(key, _ => result);
        }

        /// <summary>
        /// Compiles the generated code.
        /// </summary>
        /// <param name="code">The generated code.</param>
        /// <returns>A <see cref="Task"/>, which, when complete, provides the <see cref="Type"/> of the instance.</returns>
        private DynamicJsonType Compile(GeneratedCode code, Assembly hostAssembly)
        {
            (IEnumerable<MetadataReference> references, IEnumerable<string?> defines) = BuildMetadataReferencesAndDefines(hostAssembly);

            IEnumerable<SyntaxTree> syntaxTrees = ParseSyntaxTrees(code.GeneratedFiles, defines);

            // We are happy with the defaults (debug etc.)
            CSharpCompilationOptions options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithAssemblyIdentityComparer(DesktopAssemblyIdentityComparer.Default);
            var compilation = CSharpCompilation.Create($"Driver.GeneratedTypes_{Guid.NewGuid()}", syntaxTrees, references, options);
            using MemoryStream outputStream = new();
            EmitResult result = compilation.Emit(outputStream);

            if (!result.Success)
            {
                throw new Exception("Unable to compile generated code\r\n" + BuildCompilationErrors(result));
            }

            outputStream.Flush();
            outputStream.Position = 0;

            Assembly generatedAssembly = LoadAssembly(outputStream);

            return new(generatedAssembly.ExportedTypes.Single(t => t.FullName == code.RootType.FullyQualifiedDotnetTypeName()));

            static (IEnumerable<MetadataReference> MetadataReferences, IEnumerable<string?> Defines) BuildMetadataReferencesAndDefines(Assembly hostAssembly)
            {
                DependencyContext? ctx = DependencyContext.Default ?? DependencyContext.Load(hostAssembly);

                return ctx is null
                    ? throw new InvalidOperationException("Unable to find compilation context.")
                    : ((IEnumerable<MetadataReference> MetadataReferences, IEnumerable<string?> Defines))(from l in ctx.CompileLibraries
                                                                                                          from r in l.ResolveReferencePaths()
                                                                                                          select MetadataReference.CreateFromFile(r),
                        ctx.CompilationOptions.Defines.AsEnumerable().Union(["DYNAMIC_BUILD"]));
            }

            static IEnumerable<SyntaxTree> ParseSyntaxTrees(IReadOnlyCollection<GeneratedCodeFile> generatedTypes, IEnumerable<string?> defines)
            {
                CSharpParseOptions parseOptions = CSharpParseOptions.Default
                    .WithLanguageVersion(LanguageVersion.Preview)
                    .WithPreprocessorSymbols(defines.Where(s => s is not null).Cast<string>());
                yield return CSharpSyntaxTree.ParseText(GlobalUsingStatements, options: parseOptions, path: "GlobalUsingStatements.cs");

                foreach (GeneratedCodeFile type in generatedTypes)
                {
                    yield return CSharpSyntaxTree.ParseText(type.FileContent, options: parseOptions, path: type.FileName);
                }
            }

            static string BuildCompilationErrors(EmitResult result)
            {
                var builder = new StringBuilder();
                foreach (Diagnostic diagnostic in result.Diagnostics)
                {
                    builder.AppendLine(diagnostic.ToString());
                }

                return builder.ToString();
            }


#if NET
            Assembly LoadAssembly(MemoryStream outputStream)
            {
                return _assemblyLoadContext.LoadFromStream(outputStream);
            }
#else
            static Assembly LoadAssembly(MemoryStream outputStream)
            {
                return Assembly.Load(outputStream.ToArray());
            }
#endif
        }

        /// <summary>
        /// Generates code for the given schema with the specified virutal file name.
        /// </summary>
        /// <param name="virtualFileName">The virtual file name.</param>
        /// <param name="jsonSchema">The schema to compile.</param>
        /// <returns>A <see cref="Task"/> which, when complete, provides the generated code for the schema, with the root type declaration for that schema.</returns>
        private async Task<GeneratedCode> GenerateCodeAsync(string virtualFileName, string jsonSchema, string defaultNamespace = "Test")
        {
            ConfigureGeneration(virtualFileName, jsonSchema, defaultNamespace, out string path, out CSharpLanguageProvider languageProvider);

            TypeDeclaration rootType = await _jsonSchemaTypeBuilder.AddTypeDeclarationsAsync(new Corvus.Json.JsonReference(path), _defaultVocabulary, true);

            return GenerateCodeForRootType(languageProvider, rootType);
        }


        /// <summary>
        /// Generates code for the given schema with the specified virutal file name.
        /// </summary>
        /// <param name="virtualFileName">The virtual file name.</param>
        /// <param name="jsonSchema">The schema to compile.</param>
        /// <returns>A <see cref="Task"/> which, when complete, provides the generated code for the schema, with the root type declaration for that schema.</returns>
        private GeneratedCode GenerateCodeSync(string virtualFileName, string jsonSchema, string defaultNamespace = "Test")
        {
            ConfigureGeneration(virtualFileName, jsonSchema, defaultNamespace, out string path, out CSharpLanguageProvider languageProvider);

            TypeDeclaration rootType = _jsonSchemaTypeBuilder.AddTypeDeclarations(new Corvus.Json.JsonReference(path), _defaultVocabulary, true);

            return GenerateCodeForRootType(languageProvider, rootType);
        }

        private GeneratedCode GenerateCodeForRootType(CSharpLanguageProvider languageProvider, TypeDeclaration rootType)
        {
            IReadOnlyCollection<GeneratedCodeFile> generatedCode =
                            _jsonSchemaTypeBuilder.GenerateCodeUsing(
                            languageProvider,
                            CancellationToken.None,
                            rootType);

            // Return the fully reduced type declaration
            return new(rootType.ReducedTypeDeclaration().ReducedType, generatedCode);
        }

        private void ConfigureGeneration(string virtualFileName, string jsonSchema, string defaultNamespace, out string path, out CSharpLanguageProvider languageProvider)
        {
            path = Path.Combine(_remotesBaseDirectory!, virtualFileName);
            if (SchemaReferenceNormalization.TryNormalizeSchemaReference(path, out string? result))
            {
                path = result;
            }

            var options = new CSharpLanguageProvider.Options(
                defaultNamespace,
                alwaysAssertFormat: _validateFormat,
                optionalAsNullable: _optionalAsNullable,
                useImplicitOperatorString: _useImplicitOperatorString,
                addExplicitUsings: _addExplicitUsings);

            _jsonSchemaTypeBuilder.AddDocument(path, System.Text.Json.JsonDocument.Parse(jsonSchema));

            languageProvider = CSharpLanguageProvider.DefaultWithOptions(options);
        }

        private static string ToPascalCase(string name)
        {
            Span<char> buffer = stackalloc char[name.Length];
            name.AsSpan().CopyTo(buffer);
            Formatting.ToPascalCase(buffer);
            return buffer.ToString();
        }

#if NET
        private class TestAssemblyLoadContext : AssemblyLoadContext
        {
            public TestAssemblyLoadContext()
                : base($"TestAssemblyLoadContext_{Guid.NewGuid():N}", isCollectible: true)
            {
            }
        }
#endif
    }

    public readonly struct DynamicJsonElement(Type type, IJsonElement element) : IDisposable
    {
        private Type Type { get; } = type;
        private IJsonElement Element { get; } = element;

        public static DynamicJsonElement CastFrom<TSource>(TSource s, DynamicJsonType target)
        {
            ParameterExpression p = Expression.Parameter(typeof(TSource));
            UnaryExpression c = Expression.ConvertChecked(p, target.Type);
            UnaryExpression toIJsonElement = Expression.ConvertChecked(c, typeof(IJsonElement));
            return new(target.Type, Expression.Lambda<Func<TSource, IJsonElement>>(toIJsonElement, p).Compile()(s));
        }

        public void Dispose() => Element.ParentDocument.Dispose();

        public void EvaluateSchema(IJsonSchemaResultsCollector? resultsCollector = null)
        {
            Element.EvaluateSchema(resultsCollector);
        }

        public bool HasDotnetPropertyValue(string propertyName)
        {
            PropertyInfo property = Type.GetProperty(propertyName) ?? throw new InvalidOperationException($"Property {propertyName} of type {Type.FullName} is not a JSON element");
            object? value = property.GetValue(Element);

            return value is IJsonElement v && v.TokenType == JsonTokenType.None;
        }

        public bool CompareDotnetPropertyStringValue(string propertyName, string expectedValue)
        {
            PropertyInfo? property = Type.GetProperty(propertyName);
            if (property is null)
            {
                return false;
            }

            object? value = property.GetValue(Element);

            if (value is not IJsonElement v)
            {
                if (value is null)
                {
                    return expectedValue == "null";
                }

                throw new InvalidOperationException($"Property {propertyName} of type {Type.FullName} is not a JSON element");
            }

            if (v.TokenType != JsonTokenType.String)
            {
                return false;
            }

            string? actualValue = v.ParentDocument.GetString(v.ParentDocumentIndex, JsonTokenType.String);

            return expectedValue.Equals(actualValue);
        }

        public bool CompareNullableDotnetPropertyStringValue(string propertyName, string expectedValue)
        {
            PropertyInfo? property = Type.GetProperty(propertyName);
            if (property is null)
            {
                return false;
            }

            object? value = property.GetValue(Element);

            if (value is not IJsonElement v)
            {
                if (value is null)
                {
                    return expectedValue == "null";
                }

                throw new InvalidOperationException($"Property {propertyName} of type {Type.FullName} is not a JSON element");
            }

            if (expectedValue == "Null")
            {
                return v.TokenType == JsonTokenType.Null;
            }

            if (expectedValue == "Undefined")
            {
                return v.TokenType == JsonTokenType.None;
            }


            if (v.TokenType != JsonTokenType.String)
            {
                return false;
            }

            string? actualValue = v.ParentDocument.GetString(v.ParentDocumentIndex, JsonTokenType.String);

            return expectedValue.Equals(actualValue);
        }
    }

    public readonly struct DynamicJsonType(Type type)
    {
        public Type Type { get; } = type;

        public DynamicJsonElement ParseInstance(string json, JsonDocumentOptions options = default)
        {
            Type parsedJsonDocumentType = typeof(ParsedJsonDocument<>).MakeGenericType(Type);
            object? document = parsedJsonDocumentType
                .InvokeMember(
                    "Parse",
                    BindingFlags.Static | BindingFlags.Public | BindingFlags.InvokeMethod,
                    null,
                    null,
                    [json, options]);

            Debug.Assert(document is not null && document.GetType() == parsedJsonDocumentType);

            object? instance = parsedJsonDocumentType
                .InvokeMember(
                    "RootElement",
                    BindingFlags.Instance | BindingFlags.Public | BindingFlags.GetProperty,
                    null,
                    document,
                    []);

            Debug.Assert(instance is IJsonElement);

            return new(Type, (IJsonElement)instance);
        }
    }

    /// <summary>
    /// Creates an instance of the <see cref="GeneratedCode"/>.
    /// </summary>
    /// <param name="rootType">The root type.</param>
    /// <param name="generatedFiles">The generated files.</param>
    public readonly struct GeneratedCode(TypeDeclaration rootType, IReadOnlyCollection<GeneratedCodeFile> generatedFiles)
    {
        public TypeDeclaration RootType { get; } = rootType;

        public IReadOnlyCollection<GeneratedCodeFile> GeneratedFiles { get; } = generatedFiles;
    }
}
