//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Buffers;
using global::System.Buffers.Text;
using global::System.Runtime.CompilerServices;
using global::Corvus.Text.Json;
using global::Corvus.Text.Json.Internal;

namespace Corvus.Text.Json.Tests.MigrationModels.V5;

/// <summary>
/// Generated from JSON Schema.
/// </summary>
public readonly partial struct MigrationWithDefaults
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Examples:
    /// <example>
    /// <code>
    /// 0
    /// </code>
    /// </example>
    /// </para>
    /// </remarks>
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    public readonly partial struct CountEntity
#if NET8_0_OR_GREATER
        : IJsonElement<CountEntity>,
          IFormattable,
          ISpanFormattable,
          IUtf8SpanFormattable
#else
        : IJsonElement<CountEntity>,
          IFormattable
#endif
    {
        #pragma warning disable CS8618 // JsonDocument nullability
        private readonly IJsonDocument _parent;
        private readonly int _idx;

        #pragma warning restore CS8618 // JsonDocument nullability
        /// <summary>
        /// Initializes a new instance of the <see cref="CountEntity"/> struct.
        /// </summary>
        /// <param name="value">The value from which to construct the instance.</param>
        internal CountEntity(IJsonDocument parent, int idx)
        {
            Debug.Assert(idx >= 0);
            _parent = parent;
            _idx = idx;
        }

        /// <summary>
        /// Gets the default instance.
        /// </summary>
        public static CountEntity DefaultInstance { get; } = ParsedJsonDocument<CountEntity>.NumberConstant([.."0"u8]);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool TryGetValue(out int value) { CheckValidInstance(); return _parent.TryGetValue(_idx, out value); }

        /// <inheritdoc/>
        public JsonValueKind ValueKind => TokenType.ToValueKind();

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private JsonTokenType TokenType => _parent?.GetJsonTokenType(_idx) ?? JsonTokenType.None;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator int(CountEntity value) => value._parent.TryGetValue(value._idx, out int result) ? result : throw new FormatException();

        /// <summary>
        /// Operator ==.
        /// </summary>
        /// <param name="left">The lhs of the operator.</param>
        /// <param name="right">The rhs of the operator.</param>
        /// <returns>
        /// <c>True</c> if the values are equal.
        /// </returns>
        public static bool operator ==(in CountEntity left, in CountEntity right)
        {
            return left.Equals(right);
        }

        /// <summary>
        /// Operator !=.
        /// </summary>
        /// <param name="left">The lhs of the operator.</param>
        /// <param name="right">The rhs of the operator.</param>
        /// <returns>
        /// <c>True</c> if the values are not equal.
        /// </returns>
        public static bool operator !=(in CountEntity left, in CountEntity right)
        {
            return !left.Equals(right);
        }

        /// <summary>
        /// Operator ==.
        /// </summary>
        /// <param name="left">The lhs of the operator.</param>
        /// <param name="right">The rhs of the operator.</param>
        /// <returns>
        /// <c>True</c> if the values are equal.
        /// </returns>
        public static bool operator ==(in CountEntity left, in JsonElement right)
        {
            return left.Equals(right);
        }

        /// <summary>
        /// Operator !=.
        /// </summary>
        /// <param name="left">The lhs of the operator.</param>
        /// <param name="right">The rhs of the operator.</param>
        /// <returns>
        /// <c>True</c> if the values are not equal.
        /// </returns>
        public static bool operator !=(in CountEntity left, in JsonElement right)
        {
            return !left.Equals(right);
        }

        /// <summary>
        /// Converts the instance to a JsonElement.
        /// </summary>
        /// <param name="value">The instance of this type.</param>
        /// <returns>An instance of JsonElement, initialized from the <see cref="IJsonElement{T}"/>.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator JsonElement(CountEntity instance)
        {
            return JsonElement.From(instance);
        }

        /// <summary>
        /// Gets an instance of the JSON value from another element.
        /// </summary>
        /// <param name="value">The <see cref="IJsonElement{T}"/> value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the JSON element.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static CountEntity From<T>(in T instance)
            where T : struct, IJsonElement<T>
        {
            return new(instance.ParentDocument, instance.ParentDocumentIndex);
        }

        /// <inheritdoc/>
        public override bool Equals(object? obj)
        {
            return
                (obj is IJsonElement value && Equals(new CountEntity(value.ParentDocument, value.ParentDocumentIndex))) ||
                (obj is null && this.IsNull());
        }

        /// <summary>
        /// Equality comparison.
        /// </summary>
        /// <param name="other">The other item with which to compare.</param>
        /// <returns><see langword="true"/> if the values were equal.</returns>
        public bool Equals<T>(in T other)
            where T : struct, IJsonElement
        {
            return JsonElementHelpers.DeepEquals(this, other);
        }

        /// <summary>
        /// Compare with a normalized JSON number.
        /// </summary>
        /// <param ref="number">The normalized JSON number to compare with.</param>
        /// <returns><see langword="true"/> if the values are equal.</returns>
        public bool ValueEquals(in NormalizedJsonNumber number)
        {
            if (TokenType != JsonTokenType.Number)
            {
                return false;
            }

            JsonElementHelpers.ParseNumber(
                _parent.GetRawSimpleValueUnsafe(_idx).Span,
                out bool leftIsNegative,
                out ReadOnlySpan<byte> leftIntegral,
                out ReadOnlySpan<byte> leftFractional,
                out int leftExponent);

            return JsonElementHelpers.AreEqualNormalizedJsonNumbers(
                leftIsNegative,
                leftIntegral,
                leftFractional,
                leftExponent,
                number.IsNegative,
                number.Integral,
                number.Fractional,
                number.Exponent);
        }

        /// <inheritdoc/>
        public void WriteTo(Utf8JsonWriter writer)
        {
            CheckValidInstance();
            _parent.WriteElementTo(_idx, writer);
        }

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            if (_parent == null)
            {
                return 0;
            }

            return _parent.GetHashCode(_idx);
        }

        /// <inheritdoc/>
        public string ToString(string? format, IFormatProvider? formatProvider)
        {
            CheckValidInstance();

            return _parent.ToString(_idx, format, formatProvider);
        }

        /// <inheritdoc/>
        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {
            CheckValidInstance();

            return _parent.TryFormat(_idx, destination, out charsWritten, format, provider);
        }

        /// <inheritdoc/>
        public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {
            CheckValidInstance();

            return _parent.TryFormat(_idx, utf8Destination, out bytesWritten, format, provider);
        }
        /// <inheritdoc/>
        public override string ToString()
        {
            if (_parent is null)
            {
                return string.Empty;
            }

            return _parent.ToString(_idx);
        }

        /// <summary>
        /// Evaluate this instance against the JSON Schema for this type.
        /// </summary>
        /// <params name="resultsCollector">The (optional) results collector.</params>
        /// <returns><see langword="true" /> if the instance evaluates against the schema.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool EvaluateSchema(IJsonSchemaResultsCollector? resultsCollector = null)
        {
            return JsonSchema.Evaluate(_parent, _idx, resultsCollector);
        }

        private void CheckValidInstance()
        {
            if (_parent == null)
            {
                throw new InvalidOperationException();
            }
        }

        /// <inheritdoc/>
        void IJsonElement.CheckValidInstance() => CheckValidInstance();

#if NET
        static CountEntity IJsonElement<CountEntity>.CreateInstance(IJsonDocument parentDocument, int parentDocumentIndex) => new(parentDocument, parentDocumentIndex);
#endif

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private string DebuggerDisplay => $"CountEntity: ValueKind = {ValueKind} : \"{ToString()}\"";

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IJsonDocument IJsonElement.ParentDocument => _parent;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        int IJsonElement.ParentDocumentIndex => _idx;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        JsonTokenType IJsonElement.TokenType => TokenType;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        JsonValueKind IJsonElement.ValueKind => ValueKind;
    }
}
