// <copyright file="DynamicCompiler.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using System.Reflection;

#if NET8_0_OR_GREATER
using System.Runtime.Loader;
#endif

using System.Text;
using Corvus.Json.CodeGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.Extensions.DependencyModel;

namespace Corvus.Text.Json.Validator;

/// <summary>
/// Compiles dynamically-generated C# code into an assembly and resolves the root type.
/// </summary>
public static class DynamicCompiler
{
    private const string GlobalUsingStatements =
        """
        // <auto-generated/>

        global using global::System;
        global using global::System.Collections.Generic;
        global using global::System.IO;
        global using global::System.Linq;
        """;

#if NET8_0_OR_GREATER
    private static readonly DynamicAssemblyLoadContext PluginAssemblyLoadContext = new();
#endif

    /// <summary>
    /// Compile the generated code files and return the exported type with the given fully-qualified name.
    /// </summary>
    /// <param name="rootTypeName">The fully-qualified .NET type name of the root type.</param>
    /// <param name="generatedCode">The generated code files.</param>
    /// <param name="hostAssembly">The host assembly whose compilation context provides metadata references.</param>
    /// <returns>The compiled <see cref="Type"/>.</returns>
    /// <exception cref="InvalidOperationException">Compilation failed or the root type was not found.</exception>
    public static Type CompileGeneratedType(
        string rootTypeName,
        IReadOnlyCollection<GeneratedCodeFile> generatedCode,
        Assembly hostAssembly)
    {
        (IEnumerable<MetadataReference> references, IEnumerable<string?> defines) =
            BuildMetadataReferencesAndDefines(hostAssembly);

        IEnumerable<SyntaxTree> syntaxTrees = ParseSyntaxTrees(generatedCode, defines);

        CSharpCompilationOptions options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            .WithAssemblyIdentityComparer(DesktopAssemblyIdentityComparer.Default);

        CSharpCompilation compilation = CSharpCompilation.Create(
            $"Corvus.Dynamic.GeneratedTypes_{Guid.NewGuid()}",
            syntaxTrees,
            references,
            options);

        using MemoryStream outputStream = new();
        EmitResult result = compilation.Emit(outputStream);

        if (!result.Success)
        {
            throw new InvalidOperationException(
                "Unable to compile generated code\r\n" + BuildCompilationErrors(result));
        }

        outputStream.Flush();
        outputStream.Position = 0;

        Assembly generatedAssembly = LoadAssembly(outputStream);
        return generatedAssembly.ExportedTypes.Single(t => t.FullName == rootTypeName);
    }

    private static (IEnumerable<MetadataReference> MetadataReferences, IEnumerable<string?> Defines)
        BuildMetadataReferencesAndDefines(Assembly hostAssembly)
    {
        DependencyContext? ctx = DependencyContext.Default ?? DependencyContext.Load(hostAssembly);
        return ctx is null
            ? throw new InvalidOperationException("Unable to find compilation context.")
            : ((IEnumerable<MetadataReference> MetadataReferences, IEnumerable<string?> Defines))(
                from l in ctx.CompileLibraries
                from r in l.ResolveReferencePaths()
                select MetadataReference.CreateFromFile(r),
                ctx.CompilationOptions.Defines.AsEnumerable().Union(["DYNAMIC_BUILD"]));
    }

    private static IEnumerable<SyntaxTree> ParseSyntaxTrees(
        IReadOnlyCollection<GeneratedCodeFile> generatedTypes,
        IEnumerable<string?> defines)
    {
        CSharpParseOptions parseOptions = CSharpParseOptions.Default
            .WithLanguageVersion(LanguageVersion.Preview)
            .WithPreprocessorSymbols(defines.Where(s => s is not null).Cast<string>());

        yield return CSharpSyntaxTree.ParseText(
            GlobalUsingStatements, options: parseOptions, path: "GlobalUsingStatements.cs");

        foreach (GeneratedCodeFile type in generatedTypes)
        {
            yield return CSharpSyntaxTree.ParseText(
                type.FileContent, options: parseOptions, path: type.FileName);
        }
    }

    private static string BuildCompilationErrors(EmitResult result)
    {
        StringBuilder builder = new();
        foreach (Diagnostic diagnostic in result.Diagnostics)
        {
            builder.AppendLine(diagnostic.ToString());
        }

        return builder.ToString();
    }

#if NET8_0_OR_GREATER
    private static Assembly LoadAssembly(MemoryStream outputStream)
    {
        return PluginAssemblyLoadContext.LoadFromStream(outputStream);
    }

    private sealed class DynamicAssemblyLoadContext : AssemblyLoadContext
    {
        public DynamicAssemblyLoadContext()
            : base($"DynamicAssemblyLoadContext_{Guid.NewGuid():N}", isCollectible: true)
        {
        }
    }
#else
    private static Assembly LoadAssembly(MemoryStream outputStream)
    {
        return Assembly.Load(outputStream.ToArray());
    }
#endif
}
