//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Diagnostics;
using global::Corvus.Text.Json;
using global::Corvus.Text.Json.Internal;
using global::System.Buffers;
using global::System.Buffers.Text;
using global::System.Runtime.CompilerServices;

namespace JsonSchemaTestSuiteDraft202012LargeNumbersOfRequiredProperties;
/// <summary>
/// Generated from JSON Schema.
/// </summary>
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public readonly partial struct Required
    : IJsonElement<Required>
{
    private readonly IJsonDocument _parent;
    private readonly int _idx;

    /// <summary>
    /// Initializes a new instance of the <see cref="Required"/> struct.
    /// </summary>
    /// <param name="value">The value from which to construct the instance.</param>
    internal Required(IJsonDocument parent, int idx)
    {
        Debug.Assert(idx >= 0);
        _parent = parent;
        _idx = idx;
    }

    /// <summary>
    /// Gets the default instance.
    /// </summary>
    public static Required DefaultInstance { get; }

    /// <summary>
    /// Gets the value of the property with the given name.
    /// </summary>
    /// <param name="propertyName">The name of the property.</param>
    /// <returns>The value of the property with the given name.</returns>
    /// <exception cref="InvalidOperationException">The value is not an object.</exception>
    public JsonElement this[ReadOnlySpan<byte> propertyName]
    {
        get
        {
            CheckValidInstance();
            if (!_parent.TryGetNamedPropertyValue(_idx, propertyName, out JsonElement value))
            {
                return default;
            }

            return value;
        }
    }

    /// <summary>
    /// Gets the value of the property with the given name.
    /// </summary>
    /// <param name="propertyName">The name of the property.</param>
    /// <returns>The value of the property with the given name.</returns>
    /// <exception cref="InvalidOperationException">The value is not an object.</exception>
    public JsonElement this[ReadOnlySpan<char> propertyName]
    {
        get
        {
            CheckValidInstance();
            if (!_parent.TryGetNamedPropertyValue(_idx, propertyName, out JsonElement value))
            {
                return default;
            }

            return value;
        }
    }

    /// <summary>
    /// Gets the value of the property with the given name.
    /// </summary>
    /// <param name="propertyName">The name of the property.</param>
    /// <returns>The value of the property with the given name.</returns>
    /// <exception cref="InvalidOperationException">The value is not an object.</exception>
    public JsonElement this[string propertyName]
    {
        get
        {
            CheckValidInstance();
            if (!_parent.TryGetNamedPropertyValue(_idx, propertyName, out JsonElement value))
            {
                return default;
            }

            return value;
        }
    }

    /// <summary>
    /// Gets the (optional) <c>bar</c> property.
    /// </summary>
    public Corvus.Text.Json.JsonElement Bar
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.BarUtf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.FooUtf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo1</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo1
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo1Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo10</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo10
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo10Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo11</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo11
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo11Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo12</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo12
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo12Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo13</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo13
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo13Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo14</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo14
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo14Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo15</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo15
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo15Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo16</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo16
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo16Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo17</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo17
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo17Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo18</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo18
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo18Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo19</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo19
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo19Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo2</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo2
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo2Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo20</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo20
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo20Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo21</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo21
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo21Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo22</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo22
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo22Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo23</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo23
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo23Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo24</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo24
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo24Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo25</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo25
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo25Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo26</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo26
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo26Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo27</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo27
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo27Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo28</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo28
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo28Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo29</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo29
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo29Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo3</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo3
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo3Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo30</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo30
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo30Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo31</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo31
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo31Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo32</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo32
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo32Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo33</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo33
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo33Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo34</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo34
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo34Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo35</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo35
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo35Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo36</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo36
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo36Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo37</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo37
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo37Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo38</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo38
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo38Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo39</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo39
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo39Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo4</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo4
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo4Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo40</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo40
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo40Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo5</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo5
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo5Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo6</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo6
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo6Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo7</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo7
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo7Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo8</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo8
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo8Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the <c>foo9</c> property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the instance is valid, this property will not be <see cref="JsonValueKind.Undefined"/>, but may be <see cref="JsonValueKind.Null"/>.
    /// </para>
    /// </remarks>
    public Corvus.Text.Json.JsonElement Foo9
    {
        get
        {
            if (_parent.TryGetNamedPropertyValue(_idx, JsonPropertyNames.Foo9Utf8, out Corvus.Text.Json.JsonElement value))
            {
                return value;
            }

            return default;
        }
    }

    /// <summary>
    /// Gets the number of properties in the object.
    /// </summary>
    /// <exception cref="InvalidOperationException">The value is not an object.</exception>
    public int GetPropertyCount()
    {
        CheckValidInstance();
        return _parent.GetPropertyCount(_idx);
    }

    /// <summary>
    /// Enumerates the object.
    /// </summary>
    /// <exception cref="InvalidOperationException">The value is not an object.</exception>
    public ObjectEnumerator<JsonElement> EnumerateObject()
    {
        CheckValidInstance();
        return EnumeratorCreator.CreateObjectEnumerator<JsonElement>(_parent, _idx);
    }

    /// <inheritdoc/>
    public JsonValueKind ValueKind => TokenType.ToValueKind();

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private JsonTokenType TokenType => _parent?.GetJsonTokenType(_idx) ?? JsonTokenType.None;

    /// <summary>
    /// Operator ==.
    /// </summary>
    /// <param name="left">The lhs of the operator.</param>
    /// <param name="right">The rhs of the operator.</param>
    /// <returns>
    /// <c>True</c> if the values are equal.
    /// </returns>
    public static bool operator ==(in Required left, in Required right)
    {
        return left.Equals(right);
    }

    /// <summary>
    /// Operator !=.
    /// </summary>
    /// <param name="left">The lhs of the operator.</param>
    /// <param name="right">The rhs of the operator.</param>
    /// <returns>
    /// <c>True</c> if the values are not equal.
    /// </returns>
    public static bool operator !=(in Required left, in Required right)
    {
        return !left.Equals(right);
    }

    /// <summary>
    /// Operator ==.
    /// </summary>
    /// <param name="left">The lhs of the operator.</param>
    /// <param name="right">The rhs of the operator.</param>
    /// <returns>
    /// <c>True</c> if the values are equal.
    /// </returns>
    public static bool operator ==(in Required left, in JsonElement right)
    {
        return left.Equals(right);
    }

    /// <summary>
    /// Operator !=.
    /// </summary>
    /// <param name="left">The lhs of the operator.</param>
    /// <param name="right">The rhs of the operator.</param>
    /// <returns>
    /// <c>True</c> if the values are not equal.
    /// </returns>
    public static bool operator !=(in Required left, in JsonElement right)
    {
        return !left.Equals(right);
    }

    /// <summary>
    /// Converts the instance to a JsonElement.
    /// </summary>
    /// <param name="value">The instance of this type.</param>
    /// <returns>An instance of JsonElement, initialized from the <see cref="IJsonElement{T}"/>.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator JsonElement(Required instance)
    {
        return JsonElement.From(instance);
    }

    /// <summary>
    /// Gets an instance of the JSON value from another element.
    /// </summary>
    /// <param name="value">The <see cref="IJsonElement{T}"/> value from which to instantiate the instance.</param>
    /// <returns>An instance of this type, initialized from the JSON element.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Required From<T>(in T instance)
        where T : struct, IJsonElement<T>
    {
        return new(instance.ParentDocument, instance.ParentDocumentIndex);
    }

    /// <summary>
    ///   Parses one JSON value (including objects or arrays) from the provided span.
    /// </summary>
    /// <param name="utf8Json">The span to read.</param>
    /// <param name="options">The <see cref="JsonDocumentOptions"/> for reading.</param>
    /// <returns>
    ///   An instance representing the value (and nested values) read from the span.
    /// </returns>
    /// <remarks>
    ///   <para>
    ///     This method makes a copy of the data the reader acted on, so there is no caller
    ///     requirement to maintain data integrity beyond the return of this method.
    ///   </para>
    /// </remarks>
    /// <exception cref="JsonException">
    ///   A value could not be read from the span.
    /// </exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Required ParseValue(ReadOnlySpan<byte> utf8Json, JsonDocumentOptions options = default)
    {
        return JsonElementHelpers.ParseValue<Required>(utf8Json, options);
    }

    /// <summary>
    ///   Parses one JSON value (including objects or arrays) from the provided span.
    /// </summary>
    /// <param name="json">The span to read.</param>
    /// <param name="options">The <see cref="JsonDocumentOptions"/> for reading.</param>
    /// <returns>
    ///   An instance representing the value (and nested values) read from the span.
    /// </returns>
    /// <remarks>
    ///   <para>
    ///     This method makes a copy of the data the reader acted on, so there is no caller
    ///     requirement to maintain data integrity beyond the return of this method.
    ///   </para>
    /// </remarks>
    /// <exception cref="JsonException">
    ///   A value could not be read from the span.
    /// </exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Required ParseValue(ReadOnlySpan<char> json, JsonDocumentOptions options = default)
    {
        return JsonElementHelpers.ParseValue<Required>(json, options);
    }

    /// <summary>
    ///   Parses one JSON value (including objects or arrays) from the provided text.
    /// </summary>
    /// <param name="json">The text to read.</param>
    /// <param name="options">The <see cref="JsonDocumentOptions"/> for reading.</param>
    /// <returns>
    ///   An instance representing the value (and nested values) read from the text.
    /// </returns>
    /// <remarks>
    ///   <para>
    ///     This method makes a copy of the data the reader acted on, so there is no caller
    ///     requirement to maintain data integrity beyond the return of this method.
    ///   </para>
    /// </remarks>
    /// <exception cref="JsonException">
    ///   A value could not be read from the text.
    /// </exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Required ParseValue(string json, JsonDocumentOptions options = default)
    {
        return JsonElementHelpers.ParseValue<Required>(json, options);
    }

    /// <summary>
    ///   Parses one JSON value (including objects or arrays) from the provided reader.
    /// </summary>
    /// <param name="reader">The reader to read.</param>
    /// <returns>
    ///   An instance representing the value (and nested values) read from the reader.
    /// </returns>
    /// <remarks>
    ///   <para>
    ///     If the <see cref="Utf8JsonReader.TokenType"/> property of <paramref name="reader"/>
    ///     is <see cref="JsonTokenType.PropertyName"/> or <see cref="JsonTokenType.None"/>, the
    ///     reader will be advanced by one call to <see cref="Utf8JsonReader.Read"/> to determine
    ///     the start of the value.
    ///   </para>
    ///
    ///   <para>
    ///     Upon completion of this method, <paramref name="reader"/> will be positioned at the
    ///     final token in the JSON value. If an exception is thrown, the reader is reset to
    ///     the state it was in when the method was called.
    ///   </para>
    ///
    ///   <para>
    ///     This method makes a copy of the data the reader acted on, so there is no caller
    ///     requirement to maintain data integrity beyond the return of this method.
    ///   </para>
    /// </remarks>
    /// <exception cref="ArgumentException">
    ///   <paramref name="reader"/> is using unsupported options.
    /// </exception>
    /// <exception cref="ArgumentException">
    ///   The current <paramref name="reader"/> token does not start or represent a value.
    /// </exception>
    /// <exception cref="JsonException">
    ///   A value could not be read from the reader.
    /// </exception>
    public static Required ParseValue(ref Utf8JsonReader reader)
    {
        return JsonElementHelpers.ParseValue<Required>(ref reader);
    }

    /// <summary>
    ///   Attempts to parse one JSON value (including objects or arrays) from the provided reader.
    /// </summary>
    /// <param name="reader">The reader to read.</param>
    /// <param name="element">Receives the parsed element.</param>
    /// <returns>
    ///   <see langword="true"/> if a value was read and parsed into a JsonElement;
    ///   <see langword="false"/> if the reader ran out of data while parsing.
    ///   All other situations result in an exception being thrown.
    /// </returns>
    /// <remarks>
    ///   <para>
    ///     If the <see cref="Utf8JsonReader.TokenType"/> property of <paramref name="reader"/>
    ///     is <see cref="JsonTokenType.PropertyName"/> or <see cref="JsonTokenType.None"/>, the
    ///     reader will be advanced by one call to <see cref="Utf8JsonReader.Read"/> to determine
    ///     the start of the value.
    ///   </para>
    ///
    ///   <para>
    ///     Upon completion of this method, <paramref name="reader"/> will be positioned at the
    ///     final token in the JSON value.  If an exception is thrown, or <see langword="false"/>
    ///     is returned, the reader is reset to the state it was in when the method was called.
    ///   </para>
    ///
    ///   <para>
    ///     This method makes a copy of the data the reader acted on, so there is no caller
    ///     requirement to maintain data integrity beyond the return of this method.
    ///   </para>
    /// </remarks>
    /// <exception cref="ArgumentException">
    ///   <paramref name="reader"/> is using unsupported options.
    /// </exception>
    /// <exception cref="ArgumentException">
    ///   The current <paramref name="reader"/> token does not start or represent a value.
    /// </exception>
    /// <exception cref="JsonException">
    ///   A value could not be read from the reader.
    /// </exception>
    public static bool TryParseValue(ref Utf8JsonReader reader, out Required? result)
    {
        return JsonElementHelpers.TryParseValue<Required>(ref reader, out result);
    }

    /// <inheritdoc/>
    public override bool Equals(object? obj)
    {
        return
            (obj is IJsonElement value && Equals(new Required(value.ParentDocument, value.ParentDocumentIndex))) ||
            (obj is null && this.IsNull());
    }

    /// <summary>
    /// Equality comparison.
    /// </summary>
    /// <param name="other">The other item with which to compare.</param>
    /// <returns><see langword="true"/> if the values were equal.</returns>
    public bool Equals<T>(in T other)
        where T : struct, IJsonElement
    {
        return JsonElementHelpers.DeepEquals(this, other);
    }

    /// <inheritdoc/>
    public void WriteTo(Utf8JsonWriter writer)
    {
        CheckValidInstance();
        _parent.WriteElementTo(_idx, writer);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        if (_parent == null)
        {
            return 0;
        }

        return _parent.GetHashCode(_idx);
    }

    /// <inheritdoc/>
    public override string ToString()
    {
        if (_parent is null)
        {
            return string.Empty;
        }

        return _parent.ToString(_idx);
    }

    /// <summary>
    /// Evaluate this instance against the JSON Schema for this type.
    /// </summary>
    /// <params name="resultsCollector">The (optional) results collector.</params>
    /// <returns><see langword="true" /> if the instance evaluates against the schema.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool EvaluateSchema(IJsonSchemaResultsCollector? resultsCollector = null)
    {
        return JsonSchema.Evaluate(_parent, _idx, resultsCollector);
    }

    private void CheckValidInstance()
    {
        if (_parent == null)
        {
            throw new InvalidOperationException();
        }
    }

    /// <inheritdoc/>
    void IJsonElement.CheckValidInstance() => CheckValidInstance();

#if NET
    static Required IJsonElement<Required>.CreateInstance(IJsonDocument parentDocument, int parentDocumentIndex) => new(parentDocument, parentDocumentIndex);
#endif

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private string DebuggerDisplay => $"Required: ValueKind = {ValueKind} : \"{ToString()}\"";

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    IJsonDocument IJsonElement.ParentDocument => _parent;

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    int IJsonElement.ParentDocumentIndex => _idx;

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    JsonTokenType IJsonElement.TokenType => TokenType;

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    JsonValueKind IJsonElement.ValueKind => ValueKind;

    /// <summary>
    /// Provides UTF8 and string versions of the JSON property names on the object.
    /// </summary>
    public static class JsonPropertyNames
    {
        /// <summary>
        /// Gets the JSON property name for <see cref="Bar"/>.
        /// </summary>
        public const string Bar = "bar";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo"/>.
        /// </summary>
        public const string Foo = "foo";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo1"/>.
        /// </summary>
        public const string Foo1 = "foo1";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo10"/>.
        /// </summary>
        public const string Foo10 = "foo10";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo11"/>.
        /// </summary>
        public const string Foo11 = "foo11";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo12"/>.
        /// </summary>
        public const string Foo12 = "foo12";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo13"/>.
        /// </summary>
        public const string Foo13 = "foo13";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo14"/>.
        /// </summary>
        public const string Foo14 = "foo14";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo15"/>.
        /// </summary>
        public const string Foo15 = "foo15";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo16"/>.
        /// </summary>
        public const string Foo16 = "foo16";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo17"/>.
        /// </summary>
        public const string Foo17 = "foo17";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo18"/>.
        /// </summary>
        public const string Foo18 = "foo18";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo19"/>.
        /// </summary>
        public const string Foo19 = "foo19";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo2"/>.
        /// </summary>
        public const string Foo2 = "foo2";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo20"/>.
        /// </summary>
        public const string Foo20 = "foo20";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo21"/>.
        /// </summary>
        public const string Foo21 = "foo21";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo22"/>.
        /// </summary>
        public const string Foo22 = "foo22";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo23"/>.
        /// </summary>
        public const string Foo23 = "foo23";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo24"/>.
        /// </summary>
        public const string Foo24 = "foo24";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo25"/>.
        /// </summary>
        public const string Foo25 = "foo25";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo26"/>.
        /// </summary>
        public const string Foo26 = "foo26";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo27"/>.
        /// </summary>
        public const string Foo27 = "foo27";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo28"/>.
        /// </summary>
        public const string Foo28 = "foo28";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo29"/>.
        /// </summary>
        public const string Foo29 = "foo29";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo3"/>.
        /// </summary>
        public const string Foo3 = "foo3";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo30"/>.
        /// </summary>
        public const string Foo30 = "foo30";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo31"/>.
        /// </summary>
        public const string Foo31 = "foo31";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo32"/>.
        /// </summary>
        public const string Foo32 = "foo32";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo33"/>.
        /// </summary>
        public const string Foo33 = "foo33";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo34"/>.
        /// </summary>
        public const string Foo34 = "foo34";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo35"/>.
        /// </summary>
        public const string Foo35 = "foo35";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo36"/>.
        /// </summary>
        public const string Foo36 = "foo36";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo37"/>.
        /// </summary>
        public const string Foo37 = "foo37";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo38"/>.
        /// </summary>
        public const string Foo38 = "foo38";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo39"/>.
        /// </summary>
        public const string Foo39 = "foo39";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo4"/>.
        /// </summary>
        public const string Foo4 = "foo4";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo40"/>.
        /// </summary>
        public const string Foo40 = "foo40";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo5"/>.
        /// </summary>
        public const string Foo5 = "foo5";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo6"/>.
        /// </summary>
        public const string Foo6 = "foo6";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo7"/>.
        /// </summary>
        public const string Foo7 = "foo7";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo8"/>.
        /// </summary>
        public const string Foo8 = "foo8";

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo9"/>.
        /// </summary>
        public const string Foo9 = "foo9";

        /// <summary>
        /// Gets the JSON property name for <see cref="Bar"/>.
        /// </summary>
        public static ReadOnlySpan<byte> BarUtf8 => "bar"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo"/>.
        /// </summary>
        public static ReadOnlySpan<byte> FooUtf8 => "foo"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo1"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo1Utf8 => "foo1"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo10"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo10Utf8 => "foo10"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo11"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo11Utf8 => "foo11"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo12"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo12Utf8 => "foo12"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo13"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo13Utf8 => "foo13"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo14"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo14Utf8 => "foo14"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo15"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo15Utf8 => "foo15"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo16"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo16Utf8 => "foo16"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo17"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo17Utf8 => "foo17"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo18"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo18Utf8 => "foo18"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo19"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo19Utf8 => "foo19"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo2"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo2Utf8 => "foo2"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo20"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo20Utf8 => "foo20"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo21"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo21Utf8 => "foo21"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo22"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo22Utf8 => "foo22"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo23"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo23Utf8 => "foo23"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo24"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo24Utf8 => "foo24"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo25"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo25Utf8 => "foo25"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo26"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo26Utf8 => "foo26"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo27"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo27Utf8 => "foo27"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo28"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo28Utf8 => "foo28"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo29"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo29Utf8 => "foo29"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo3"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo3Utf8 => "foo3"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo30"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo30Utf8 => "foo30"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo31"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo31Utf8 => "foo31"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo32"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo32Utf8 => "foo32"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo33"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo33Utf8 => "foo33"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo34"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo34Utf8 => "foo34"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo35"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo35Utf8 => "foo35"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo36"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo36Utf8 => "foo36"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo37"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo37Utf8 => "foo37"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo38"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo38Utf8 => "foo38"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo39"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo39Utf8 => "foo39"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo4"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo4Utf8 => "foo4"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo40"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo40Utf8 => "foo40"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo5"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo5Utf8 => "foo5"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo6"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo6Utf8 => "foo6"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo7"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo7Utf8 => "foo7"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo8"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo8Utf8 => "foo8"u8;

        /// <summary>
        /// Gets the JSON property name for <see cref="Foo9"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo9Utf8 => "foo9"u8;
    }

    /// <summary>
    /// Provides escaped UTF-8 versions of the JSON property names on the object.
    /// </summary>
    private static class JsonPropertyNamesEscaped
    {
        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Bar"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Bar => "bar"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo => "foo"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo1"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo1 => "foo1"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo10"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo10 => "foo10"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo11"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo11 => "foo11"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo12"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo12 => "foo12"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo13"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo13 => "foo13"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo14"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo14 => "foo14"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo15"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo15 => "foo15"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo16"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo16 => "foo16"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo17"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo17 => "foo17"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo18"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo18 => "foo18"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo19"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo19 => "foo19"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo2"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo2 => "foo2"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo20"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo20 => "foo20"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo21"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo21 => "foo21"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo22"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo22 => "foo22"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo23"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo23 => "foo23"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo24"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo24 => "foo24"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo25"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo25 => "foo25"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo26"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo26 => "foo26"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo27"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo27 => "foo27"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo28"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo28 => "foo28"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo29"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo29 => "foo29"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo3"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo3 => "foo3"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo30"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo30 => "foo30"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo31"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo31 => "foo31"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo32"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo32 => "foo32"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo33"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo33 => "foo33"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo34"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo34 => "foo34"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo35"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo35 => "foo35"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo36"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo36 => "foo36"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo37"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo37 => "foo37"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo38"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo38 => "foo38"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo39"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo39 => "foo39"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo4"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo4 => "foo4"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo40"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo40 => "foo40"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo5"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo5 => "foo5"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo6"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo6 => "foo6"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo7"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo7 => "foo7"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo8"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo8 => "foo8"u8;

        /// <summary>
        /// Gets the escaped UTF-8 JSON property name for <see cref="Foo9"/>.
        /// </summary>
        public static ReadOnlySpan<byte> Foo9 => "foo9"u8;
    }
}
