// <copyright file="CorePartial.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using Corvus.Json.CodeGeneration;

namespace Corvus.Text.Json.CodeGeneration;

/// <summary>
/// Provides the core file for a type declaration.
/// </summary>
public sealed class CorePartial : ICodeFileBuilder
{
    private CorePartial()
    {
    }

    /// <summary>
    /// Gets a singleton instance of the <see cref="CorePartial"/> builder.
    /// </summary>
    public static CorePartial Instance { get; } = new();

    /// <inheritdoc/>
    public CodeGenerator EmitFile(CodeGenerator generator, TypeDeclaration typeDeclaration)
    {
        FrameworkType addExplicitUsings = typeDeclaration.AddExplicitUsings() ? FrameworkType.All : FrameworkType.NotEmitted;

        return generator
            .BeginFile(typeDeclaration, string.Empty)
                .AppendAutoGeneratedHeader()
                .AppendLine()
                .AppendLine("#nullable enable")
                .AppendLine()
                .AppendUsings(
                    new("global::System", addExplicitUsings),
                    new("global::System.Diagnostics", addExplicitUsings),
                    new("global::System.Diagnostics.CodeAnalysis", addExplicitUsings),
                    "System.Buffers",
                    "System.Buffers.Text",
                    "System.Runtime.CompilerServices",
                    "Corvus.Text.Json",
                    "Corvus.Text.Json.Internal")
                .AppendLine()
                .BeginTypeDeclarationNesting(typeDeclaration)
                    .AppendDocumentation(typeDeclaration)
                    .AppendDebuggerDisplay()
                    .BeginPartialStructDeclaration(
                        typeDeclaration.DotnetAccessibility(),
                        typeDeclaration.DotnetTypeName(),
                        interfaces: [
                            typeDeclaration.GetIJsonElementInterface(forMutable: false)
                            ])
                        .PushJsonSchemaClassNameAndScope()
                        .PushJsonPropertyNamesEscapedClassNameAndScope()
                        .PushJsonPropertyNamesClassNameAndScope()
                        .PushBuilderClassNameAndScope()
                        .PushSourceClassNameAndScope()
                        .AppendBackingFields()
                        .AppendInternalConstructor(typeDeclaration)
                        .AppendDefaultInstanceStaticProperty(typeDeclaration)
                        .AppendArrayRankStaticProperty(typeDeclaration)
                        .AppendArrayDimensionStaticProperty(typeDeclaration)
                        .AppendArrayValueBufferSizeStaticProperty(typeDeclaration)
                        .AppendArrayIndexerProperties(typeDeclaration)
                        .AppendObjectIndexerProperties(typeDeclaration)
                        .AppendGetArrayLength(typeDeclaration)
                        .AppendGetPropertyCount(typeDeclaration)
                        .AppendValueKindProperty()
                        .AppendTokenTypeProperty()
                        .AppendConversionToCompositionTypes(typeDeclaration)
                        .AppendBinaryOperator(typeDeclaration, "bool", "==", "return left.Equals(right);", "<c>True</c> if the values are equal.")
                        .AppendBinaryOperator(typeDeclaration, "bool", "!=", "return !left.Equals(right);", "<c>True</c> if the values are not equal.")
                        .AppendBinaryOperator(typeDeclaration, "JsonElement", "bool", "==", "return left.Equals(right);", "<c>True</c> if the values are equal.")
                        .AppendBinaryOperator(typeDeclaration, "JsonElement", "bool", "!=", "return !left.Equals(right);", "<c>True</c> if the values are not equal.")
                        .AppendJsonElementConversionOperator(typeDeclaration)
                        .AppendFromFactoryMethod(typeDeclaration)
                        .AppendEqualsOverloads(typeDeclaration)
                        .AppendWriteToMethod()
                        .AppendGetHashCodeAndToStringMethods(forMutable: false)
                        .AppendEvaluateSchemaMethod()
                        .AppendCheckValidInstance()
                        .AppendCreateInstance(typeDeclaration)
                        .AppendDebuggerDisplayProperty(typeDeclaration)
                        .AppendIJsonElementExplicitImplementation()
                        .AppendTryGetAsCompositionTypeMethods(typeDeclaration)
                        .AppendMatchMethods(typeDeclaration)
                        .AppendSourceAndBuilder(typeDeclaration)
                        .AppendJsonPropertyNames(typeDeclaration)
                        .AppendJsonPropertyNamesEscaped(typeDeclaration)
                        .PopSourceClassNameAndScope()
                        .PopBuilderClassNameAndScope()
                        .PopJsonPropertyNamesClassNameAndScope()
                        .PopJsonPropertyNamesEscapedClassNameAndScope()
                        .PopJsonSchemaClassNameAndScope()
                    .EndClassStructOrEnumDeclaration()
                .EndTypeDeclarationNesting(typeDeclaration)
                .EndNamespace()
            .EndFile(typeDeclaration, string.Empty);
    }
}
