// Derived from code licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licensed this code under the MIT license.

using System.Collections.Generic;
using Corvus.Json.CodeGeneration;

namespace Corvus.Text.Json.CodeGeneration;

/// <summary>
/// Provides the JsonSchema file for a type declaration.
/// </summary>
public sealed class JsonSchemaPartial : ICodeFileBuilder
{
    private JsonSchemaPartial()
    {
    }

    /// <summary>
    /// Gets a singleton instance of the <see cref="JsonSchemaPartial"/> builder.
    /// </summary>
    public static JsonSchemaPartial Instance { get; } = new();

    /// <inheritdoc/>
    public CodeGenerator EmitFile(CodeGenerator generator, TypeDeclaration typeDeclaration)
    {
        FrameworkType addExplicitUsings = typeDeclaration.AddExplicitUsings() ? FrameworkType.All : FrameworkType.NotEmitted;

        generator
            .BeginFile(typeDeclaration, "JsonSchema")
                .AppendAutoGeneratedHeader()
                .AppendLine()
                .AppendLine("#nullable enable")
                .AppendLine()
                .AppendUsings(
                    new("global::System", addExplicitUsings),
                    new("global::System.Diagnostics"),
                    new("global::System.Diagnostics.CodeAnalysis"),
                    "global::System.Buffers",
                    "global::System.Buffers.Text",
                    "global::System.Runtime.CompilerServices",
                    RequiresRegularExpressions(typeDeclaration) ? "global::System.Text.RegularExpressions" : ConditionalCodeSpecification.DoNotEmit,
                    "global::Corvus.Text.Json",
                    "global::Corvus.Text.Json.Internal")
                .AppendLine()
                .BeginTypeDeclarationNesting(typeDeclaration)
                    .AppendDocumentation(typeDeclaration)
                    .AppendDebuggerDisplay()
                    .BeginPartialStructDeclaration(
                        typeDeclaration.DotnetAccessibility(),
                        typeDeclaration.DotnetTypeName(),
                        interfaces: [
                            typeDeclaration.GetIJsonElementInterface(forMutable: false)
                            ])
                        .PushJsonSchemaClassNameAndScope()
                        .PushJsonPropertyNamesEscapedClassNameAndScope()
                        .PushJsonPropertyNamesClassNameAndScope()
                        .PushBuilderClassNameAndScope()
                        .PushSourceClassNameAndScope()
                        .PushConstantsClassNameAndScope()
                        .PushEnumValuesClassNameAndScope()
                        .PushMutableClassNameAndScope()
                        .AppendConstantsClass(typeDeclaration)
                        .AppendEnumValuesClass(typeDeclaration)
                        .AppendSeparatorLine()
                        .BeginPublicStaticPartialClassDeclaration(generator.JsonSchemaClassName())
                            .AppendJsonSchemaClassSetup(typeDeclaration)
                            .AppendRegexValidationFields(typeDeclaration)
                            .AppendSchemaLocationStaticProperty(typeDeclaration)
                            .AppendSubschemaEvaluationPathStaticProperties(typeDeclaration)
                            .AppendJsonSchemaEvaluateMethod(typeDeclaration)
                            .AppendRegexValidationFactoryMethods(typeDeclaration)
                            .AppendPushChildContextMethods(typeDeclaration)
                        .EndClassStructOrEnumDeclaration()
                        .PopMutableClassNameAndScope()
                        .PopEnumValuesClassNameAndScope()
                        .PopConstantsClassNameAndScope()
                        .PopSourceClassNameAndScope()
                        .PopBuilderClassNameAndScope()
                        .PopJsonPropertyNamesClassNameAndScope()
                        .PopJsonPropertyNamesEscapedClassNameAndScope()
                        .PopJsonSchemaClassNameAndScope()
                    .EndClassStructOrEnumDeclaration()
                .EndTypeDeclarationNesting(typeDeclaration)
                .EndNamespace()
            .EndFile(typeDeclaration, string.Empty);

        return generator;
    }

    private static bool RequiresRegularExpressions(TypeDeclaration typeDeclaration)
    {
        return typeDeclaration.ValidationRegularExpressions() is IReadOnlyDictionary<IValidationRegexProviderKeyword, IReadOnlyList<string>> regexes && regexes.Count != 0;
    }
}
