// <copyright file="JsonSchemaPartial.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using Corvus.Json.CodeGeneration;

namespace Corvus.Text.Json.CodeGeneration;

/// <summary>
/// Provides the JsonSchema file for a type declaration.
/// </summary>
public sealed class JsonSchemaPartial : ICodeFileBuilder
{
    private JsonSchemaPartial()
    {
    }

    /// <summary>
    /// Gets a singleton instance of the <see cref="JsonSchemaPartial"/> builder.
    /// </summary>
    public static JsonSchemaPartial Instance { get; } = new();

    /// <inheritdoc/>
    public CodeGenerator EmitFile(CodeGenerator generator, TypeDeclaration typeDeclaration)
    {
        FrameworkType addExplicitUsings = typeDeclaration.AddExplicitUsings() ? FrameworkType.All : FrameworkType.NotEmitted;

        return generator
            .BeginFile(typeDeclaration, "JsonSchema")
                .AppendAutoGeneratedHeader()
                .AppendLine()
                .AppendLine("#nullable enable")
                .AppendLine()
                .AppendUsings(
                    new("global::System", addExplicitUsings),
                    new("global::System.Diagnostics", addExplicitUsings),
                    new("global::System.Diagnostics.CodeAnalysis", addExplicitUsings),
                    "System.Buffers",
                    "System.Buffers.Text",
                    "System.Runtime.CompilerServices",
                    "Corvus.Text.Json",
                    "Corvus.Text.Json.Internal")
                .AppendLine()
                .BeginTypeDeclarationNesting(typeDeclaration)
                    .AppendDocumentation(typeDeclaration)
                    .AppendDebuggerDisplay()
                    .BeginPartialStructDeclaration(
                        typeDeclaration.DotnetAccessibility(),
                        typeDeclaration.DotnetTypeName(),
                        interfaces: [
                            typeDeclaration.GetIJsonElementInterface(forMutable: false)
                            ])
                        .PushJsonSchemaClassNameAndScope()
                        .PushJsonPropertyNamesEscapedClassNameAndScope()
                        .PushJsonPropertyNamesClassNameAndScope()
                        .PushBuilderClassNameAndScope()
                        .PushSourceClassNameAndScope()
                        .BeginPublicStaticClassDeclaration(generator.JsonSchemaClassName())
                            .AppendJsonSchemaEvaluateMethod(typeDeclaration)
                        .EndClassStructOrEnumDeclaration()
                        .PopSourceClassNameAndScope()
                        .PopBuilderClassNameAndScope()
                        .PopJsonPropertyNamesClassNameAndScope()
                        .PopJsonPropertyNamesEscapedClassNameAndScope()
                        .PopJsonSchemaClassNameAndScope()
                    .EndClassStructOrEnumDeclaration()
                .EndTypeDeclarationNesting(typeDeclaration)
                .EndNamespace()
            .EndFile(typeDeclaration, string.Empty);
    }
}
