// <copyright file="CorePartial.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using Corvus.Json.CodeGeneration;

namespace Corvus.Text.Json.CodeGeneration;

/// <summary>
/// Provides the core file for a mutable type declaration.
/// </summary>
public sealed class MutableCorePartial : ICodeFileBuilder
{
    private MutableCorePartial()
    {
    }

    /// <summary>
    /// Gets a singleton instance of the <see cref="MutableCorePartial"/> builder.
    /// </summary>
    public static MutableCorePartial Instance { get; } = new();

    /// <inheritdoc/>
    public CodeGenerator EmitFile(CodeGenerator generator, TypeDeclaration typeDeclaration)
    {
        FrameworkType addExplicitUsings = typeDeclaration.AddExplicitUsings() ? FrameworkType.All : FrameworkType.NotEmitted;

        return generator
            .BeginFile(typeDeclaration, string.Empty)
                .AppendAutoGeneratedHeader()
                .AppendLine()
                .AppendLine("#nullable enable")
                .AppendLine()
                .AppendUsings(
                    new("global::System", addExplicitUsings),
                    new("global::System.Diagnostics", addExplicitUsings),
                    new("global::System.Diagnostics.CodeAnalysis", addExplicitUsings),
                    "System.Buffers",
                    "System.Runtime.CompilerServices",
                    "Corvus.Text.Json",
                    "Corvus.Text.Json.Internal")
                .AppendLine()
                .BeginTypeDeclarationNesting(typeDeclaration)
                    .AppendDocumentation(typeDeclaration)
                    .AppendDebuggerDisplay()
                    .BeginReadonlyPartialStructDeclaration(
                        typeDeclaration.DotnetAccessibility(),
                        typeDeclaration.DotnetTypeName())
                        .PushJsonSchemaClassNameAndScope()
                        // Begin the mutable part of the declaration
                        .BeginReadonlyPartialStructDeclaration(
                            GeneratedTypeAccessibility.Public,
                            "Mutable",
                            interfaces: [
                                typeDeclaration.GetIJsonElementInterface(forMutable: true)
                                ])
                            .AppendBackingFields(forMutable: true)
                            .AppendInternalConstructor(typeDeclaration, forMutable: true)
                            .AppendValueKindProperty()
                            .AppendTokenTypeProperty()
                            .AppendConversionToCompositionTypes(typeDeclaration)
                            .AppendBinaryOperator("Mutable", "Mutable", "bool", "==", "return left.Equals(right);", "<c>True</c> if the values are equal.")
                            .AppendBinaryOperator("Mutable", "Mutable", "bool", "!=", "return !left.Equals(right);", "<c>True</c> if the values are not equal.")
                            .AppendBinaryOperator("Mutable", "JsonElement", "bool", "==", "return left.Equals(right);", "<c>True</c> if the values are equal.")
                            .AppendBinaryOperator("Mutable", "JsonElement", "bool", "!=", "return !left.Equals(right);", "<c>True</c> if the values are not equal.")
                            .AppendJsonElementConversionOperator(typeDeclaration)
                            .AppendMutableConversionOperators(typeDeclaration)
                            .AppendFromFactoryMethod(typeDeclaration, forMutable: true)
                            .AppendEqualsOverloads(typeDeclaration)
                            .AppendWriteToMethod()
                            .AppendGetHashCodeAndToStringMethods(forMutable: true)
                            .AppendEvaluateSchemaMethod()
                            .AppendCheckValidInstance(forMutable: true)
                            .AppendCreateInstance(typeDeclaration, forMutable: true)
                            .AppendDebuggerDisplayProperty(typeDeclaration, forMutable: true)
                            .AppendIJsonElementExplicitImplementation()
                            .AppendMatchMethods(typeDeclaration, forMutable: true)
                            .AppendTryGetAsCompositionTypeMethods(typeDeclaration)
                        .EndClassStructOrEnumDeclaration()
                    .PopJsonSchemaClassNameAndScope()
                    .EndClassStructOrEnumDeclaration()
                .EndTypeDeclarationNesting(typeDeclaration)
                .EndNamespace()
            .EndFile(typeDeclaration, string.Empty);
    }
}
