// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Corvus.Json.CodeGeneration;

namespace Corvus.Text.Json.CodeGeneration;

/// <summary>
/// Provides the core file for a mutable type declaration.
/// </summary>
public sealed class MutableCorePartial : ICodeFileBuilder
{
    private MutableCorePartial()
    {
    }

    /// <summary>
    /// Gets a singleton instance of the <see cref="MutableCorePartial"/> builder.
    /// </summary>
    public static MutableCorePartial Instance { get; } = new();

    /// <inheritdoc/>
    public CodeGenerator EmitFile(CodeGenerator generator, TypeDeclaration typeDeclaration)
    {
        FrameworkType addExplicitUsings = typeDeclaration.AddExplicitUsings() ? FrameworkType.All : FrameworkType.NotEmitted;

        return generator
            .BeginFile(typeDeclaration, "Mutable")
                .AppendAutoGeneratedHeader()
                .AppendLine()
                .AppendLine("#nullable enable")
                .AppendLine()
                .AppendUsings(
                    new("global::System", addExplicitUsings),
                    new("global::System.Diagnostics"),
                    new("global::System.Diagnostics.CodeAnalysis"),
                    "global::System.Buffers",
                    "global::System.Buffers.Text",
                    "global::System.Runtime.CompilerServices",
                    "global::Corvus.Text.Json",
                    "global::Corvus.Text.Json.Internal")
                .AppendLine()
                .BeginTypeDeclarationNesting(typeDeclaration)
                    .AppendDocumentation(typeDeclaration)
                    .AppendDebuggerDisplay()
                    .BeginPartialStructDeclaration(
                        typeDeclaration.DotnetAccessibility(),
                        typeDeclaration.DotnetTypeName())
                        .PushJsonSchemaClassNameAndScope()
                        .PushJsonPropertyNamesEscapedClassNameAndScope()
                        .PushJsonPropertyNamesClassNameAndScope()
                        .PushBuilderClassNameAndScope()
                        .PushSourceClassNameAndScope()
                        .PushConstantsClassNameAndScope()
                        // Begin the mutable part of the declaration
                        .BeginPartialStructDeclaration(
                            GeneratedTypeAccessibility.Public,
                            "Mutable",
                            interfaces: [
                                typeDeclaration.GetIJsonElementInterface(forMutable: true)
                                ],
                            isReadOnly: false)
                            .AppendBackingFields(forMutable: true)
                            .AppendInternalConstructor(typeDeclaration, forMutable: true)
                            .AppendValueKindProperty()
                            .AppendTokenTypeProperty()
                            .AppendConversionToCompositionTypes(typeDeclaration, forMutable: true)
                            .AppendBinaryOperator("Mutable", "Mutable", "bool", "==", "return left.Equals(right);", "<c>True</c> if the values are equal.")
                            .AppendBinaryOperator("Mutable", "Mutable", "bool", "!=", "return !left.Equals(right);", "<c>True</c> if the values are not equal.")
                            .AppendBinaryOperator("Mutable", "JsonElement", "bool", "==", "return left.Equals(right);", "<c>True</c> if the values are equal.")
                            .AppendBinaryOperator("Mutable", "JsonElement", "bool", "!=", "return !left.Equals(right);", "<c>True</c> if the values are not equal.")
                            .AppendJsonElementConversionOperator(typeDeclaration, forMutable: true)
                            .AppendMutableConversionOperators(typeDeclaration)
                            .AppendFromFactoryMethod(typeDeclaration, forMutable: true)
                            .AppendArrayIndexerProperties(typeDeclaration, forMutable: true)
                            .AppendObjectIndexerProperties(typeDeclaration, forMutable: true)
                            .AppendObjectProperties(typeDeclaration, forMutable:true)
                            .AppendGetArrayLength(typeDeclaration)
                            .AppendGetPropertyCount(typeDeclaration)
                            .AppendEnumerateArray(typeDeclaration, forMutable: true)
                            .AppendEnumerateObject(typeDeclaration, forMutable: true)
                            .AppendEqualsOverloads(typeDeclaration)
                            .AppendValueEqualsOverloads(typeDeclaration)
                            .AppendObjectPropertySetters(typeDeclaration)
                            .AppendApplyObjectCompositionTypes(typeDeclaration)
                            .AppendWriteToMethod()
                            .AppendGetHashCodeAndToStringMethods(forMutable: true)
                            .AppendEvaluateSchemaMethod()
                            .AppendCheckValidInstance(forMutable: true)
                            .AppendCreateInstance(typeDeclaration, forMutable: true)
                            .AppendDebuggerDisplayProperty(typeDeclaration, forMutable: true)
                            .AppendArrayMutators(typeDeclaration)
                            ////.AppendObjectMutators(typeDeclaration)
                            .AppendIJsonElementExplicitImplementation()
                            .AppendMatchMethods(typeDeclaration, forMutable: true)
                            .AppendTryGetAsCompositionTypeMethods(typeDeclaration, forMutable: true)
                        .EndClassStructOrEnumDeclaration()
                        .AppendSourceAndBuilder(typeDeclaration)
                        .PopConstantsClassNameAndScope()
                        .PopSourceClassNameAndScope()
                        .PopBuilderClassNameAndScope()
                        .PopJsonPropertyNamesClassNameAndScope()
                        .PopJsonPropertyNamesEscapedClassNameAndScope()
                        .PopJsonSchemaClassNameAndScope()
                    .EndClassStructOrEnumDeclaration()
                .EndTypeDeclarationNesting(typeDeclaration)
                .EndNamespace()
            .EndFile(typeDeclaration, string.Empty);
    }
}
