// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90
{
    public partial class Net90GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>>? _DictionaryStringHighLowTemps;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>> DictionaryStringHighLowTemps
        #nullable enable annotations
        {
            get => _DictionaryStringHighLowTemps ??= (global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>>)Options.GetTypeInfo(typeof(global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>));
        }
        
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>> Create_DictionaryStringHighLowTemps(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>>(options, out global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>> jsonTypeInfo))
            {
                var info = new global::Corvus.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>>
                {
                    ObjectCreator = () => new global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>(),
                    SerializeHandler = DictionaryStringHighLowTempsSerializeHandler
                };
                
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateDictionaryInfo<global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>, string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>(options, info);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void DictionaryStringHighLowTempsSerializeHandler(global::Corvus.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.Dictionary<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps>? value)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            foreach (global::System.Collections.Generic.KeyValuePair<string, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.HighLowTemps> entry in value)
            {
                writer.WritePropertyName(entry.Key);
                HighLowTempsSerializeHandler(writer, entry.Value);
            }

            writer.WriteEndObject();
        }
    }
}
