// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90
{
    public partial class Net90GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList>? _MyLinkedList;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList> MyLinkedList
        #nullable enable annotations
        {
            get => _MyLinkedList ??= (global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList>)Options.GetTypeInfo(typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList));
        }
        
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList> Create_MyLinkedList(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList>(options, out global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList> jsonTypeInfo))
            {
                var objectInfo = new global::Corvus.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList((int)args[0], (global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)args[1]),
                    PropertyMetadataInitializer = _ => MyLinkedListPropInit(options),
                    ConstructorParameterMetadataInitializer = MyLinkedListCtorParamInit,
                    ConstructorAttributeProviderFactory = static () => typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList).GetConstructor(InstanceMemberBindingFlags, binder: null, new[] {typeof(int), typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)}, modifiers: null),
                    SerializeHandler = MyLinkedListSerializeHandler,
                };
                
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[] MyLinkedListPropInit(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfo[2];

            var info0 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList),
                Converter = null,
                Getter = static obj => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)obj).Value,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)obj).Value = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Value",
                JsonPropertyName = null,
                AttributeProviderFactory = static () => typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList).GetProperty("Value", InstanceMemberBindingFlags, null, typeof(int), global::System.Array.Empty<global::System.Type>(), null),
            };
            
            properties[0] = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info0);

            var info1 = new global::Corvus.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList),
                Converter = null,
                Getter = static obj => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)obj).Nested,
                Setter = static (obj, value) => ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)obj).Nested = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Nested",
                JsonPropertyName = null,
                AttributeProviderFactory = static () => typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList).GetProperty("Nested", InstanceMemberBindingFlags, null, typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList), global::System.Array.Empty<global::System.Type>(), null),
            };
            
            properties[1] = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList>(options, info1);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void MyLinkedListSerializeHandler(global::Corvus.Text.Json.Utf8JsonWriter writer, global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList? value)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteNumber(PropName_Value, ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)value).Value);
            writer.WritePropertyName(PropName_Nested);
            MyLinkedListSerializeHandler(writer, ((global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList)value).Nested);

            writer.WriteEndObject();
        }

        private static global::Corvus.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] MyLinkedListCtorParamInit() => new global::Corvus.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
        {
            new()
            {
                Name = "value",
                ParameterType = typeof(int),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = null,
                IsNullable = false,
            },

            new()
            {
                Name = "nested",
                ParameterType = typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.MyLinkedList),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = null,
                IsNullable = true,
            },
        };
    }
}
