// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90
{
    public partial class Net90GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter>? _ClassWithCustomConverter;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter> ClassWithCustomConverter
        #nullable enable annotations
        {
            get => _ClassWithCustomConverter ??= (global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter>)Options.GetTypeInfo(typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter));
        }
        
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter> Create_ClassWithCustomConverter(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter>(options, out global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter> jsonTypeInfo))
            {
                global::Corvus.Text.Json.Serialization.JsonConverter converter = ExpandConverter(typeof(global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter), new global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter.CustomConverter(), options);
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90.ClassWithCustomConverter> (options, converter);
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }
    }
}
