// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Corvus.Text.Json.Tests.SourceGenRegressionTests.Net90
{
    public partial class Net90GeneratedContext
    {
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<string>? _String;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<string> String
        #nullable enable annotations
        {
            get => _String ??= (global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)Options.GetTypeInfo(typeof(string));
        }
        
        private global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<string> Create_String(global::Corvus.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<string>(options, out global::Corvus.Text.Json.Serialization.Metadata.JsonTypeInfo<string> jsonTypeInfo))
            {
                jsonTypeInfo = global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<string>(options, global::Corvus.Text.Json.Serialization.Metadata.JsonMetadataServices.StringConverter);
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }
    }
}
