// <copyright file="CorePartial.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using Corvus.Json.CodeGeneration;

namespace Corvus.Text.Json.CodeGeneration;

/// <summary>
/// Provides the core file for a type declaration.
/// </summary>
public sealed class CorePartial : ICodeFileBuilder
{
    private CorePartial()
    {
    }

    /// <summary>
    /// Gets a singleton instance of the <see cref="CorePartial"/> builder.
    /// </summary>
    public static CorePartial Instance { get; } = new();

    /// <inheritdoc/>
    public CodeGenerator EmitFile(CodeGenerator generator, TypeDeclaration typeDeclaration)
    {
        FrameworkType addExplicitUsings = typeDeclaration.AddExplicitUsings() ? FrameworkType.All : FrameworkType.NotEmitted;

        return generator
            .BeginFile(typeDeclaration, string.Empty)
                .AppendAutoGeneratedHeader()
                .AppendLine()
                .AppendLine("#nullable enable")
                .AppendLine()
                .AppendUsings(
                    new("global::System", addExplicitUsings),
                    new("global::System.Diagnostics", addExplicitUsings),
                    new("global::System.Diagnostics.CodeAnalysis", addExplicitUsings),
                    "System.Buffers",
                    "System.Runtime.CompilerServices",
                    "Corvus.Text.Json",
                    "Corvus.Text.Json.Internal")
                .AppendLine()
                .BeginTypeDeclarationNesting(typeDeclaration)
                    .AppendDocumentation(typeDeclaration)
                    .BeginReadonlyPartialStructDeclaration(
                        typeDeclaration.DotnetAccessibility(),
                        typeDeclaration.DotnetTypeName(),
                        interfaces: [
                            typeDeclaration.GetIJsonElementInterface()
                            ])
                        .PushJsonSchemaClassNameAndScope()
                        .AppendBackingFields()
                        .AppendInternalConstructor(typeDeclaration)
//                      TODO: move this into the JsonSchema class, once we have it.
//                        .AppendSchemaLocationStaticProperty(typeDeclaration)
                        .AppendDefaultInstanceStaticProperty(typeDeclaration)
                        .AppendValueKindProperty(typeDeclaration)
                        .AppendTokenTypeProperty(typeDeclaration)
                        .AppendConversionToCompositionTypes(typeDeclaration)
                        .AppendBinaryOperator(typeDeclaration, "bool", "==", "return left.DeepEquals(right);", "<c>True</c> if the values are equal.")
                        .AppendBinaryOperator(typeDeclaration, "bool", "!=", "return !left.DeepEquals(right);", "<c>True</c> if the values are not equal.")
                        .AppendFromFactoryMethod(typeDeclaration)
                        .AppendEqualsOverloads(typeDeclaration)
//                      TODO: we are working on this now
                        //.AppendWriteToMethod(typeDeclaration)
                        //.AppendGetHashCodeAndToStringMethods(typeDeclaration)
                        //.AppendValidateMethodForNoValidation(typeDeclaration)
                        //.AppendMatchMethods(typeDeclaration)
                        //.AppendTryGetMethods(typeDeclaration)
                        //.PopValidationClassNameAndScope()
                    .EndClassOrStructDeclaration()
                .EndTypeDeclarationNesting(typeDeclaration)
                .EndNamespace()
            .EndFile(typeDeclaration, string.Empty);
    }
}
